# Generated by ModelForge.
# Declares this model's DecisionModelsService contract.
# See IMPLEMENTATION_GUIDE.md.

from registry.model_definition import ModelDefinition
from schemas.model_requests import GenericModelExecutionRequest
from .executor import execute_topsis_2tuple
from .examples import (
    TOPSIS_2TUPLE_REQUEST_EXAMPLES,
    TOPSIS_2TUPLE_RESPONSE_EXAMPLES,
)


MODEL_DEFINITION = ModelDefinition(
    api_model_key="topsis_2tuple",
    api_endpoint_path="/topsis_2tuple",
    request_model=GenericModelExecutionRequest,
    handler=execute_topsis_2tuple,
    display_name="2-TUPLE TOPSIS",
    small_description="TOPSIS method for multi-expert decision making using the 2-tuple linguistic representation model.",
    extended_description="Ranks alternatives using linguistic 2-tuples, criteria weights, expert weights, and benefit/cost criterion types.",
    request_examples=TOPSIS_2TUPLE_REQUEST_EXAMPLES,
    response_examples=TOPSIS_2TUPLE_RESPONSE_EXAMPLES,
    more_info_url=None,
    implementation_status="ready",
    model_kind="issue",
    evaluation_structure_key="alternativeCriteriaMatrix",
    supports_creator_criteria_weighting=False,
    supports_expert_criteria_weighting=False,
    supports_consensus=False,
    supports_consensus_simulation=False,
    is_multi_criteria=True,
    uses_criteria_weights=True,
    uses_expert_weights=True,
    uses_fuzzy_criteria_weights=False,
    uses_criterion_types=True,
    supported_expression_domains=[{'typeKey': 'linguistic2Tuple', 'constraints': {}}],
    parameters=[],
)
