# Generated by ModelForge.
# API documentation examples only.
# See IMPLEMENTATION_GUIDE.md.

from typing import Any


LINGUISTIC_2TUPLE_DOMAIN: dict[str, Any] = {
    "name": "Five-level linguistic 2-tuple scale",
    "typeKey": "linguistic2Tuple",
    "definition": {
        "labelCount": 5,
        "labels": [
            {
                "key": "s0",
                "label": "Very Low",
                "index": 0,
            },
            {
                "key": "s1",
                "label": "Low",
                "index": 1,
            },
            {
                "key": "s2",
                "label": "Medium",
                "index": 2,
            },
            {
                "key": "s3",
                "label": "High",
                "index": 3,
            },
            {
                "key": "s4",
                "label": "Very High",
                "index": 4,
            },
        ],
    },
}


TOPSIS_2TUPLE_REQUEST_EXAMPLES: dict[
    str,
    dict[str, Any],
] = {
    "basic_linguistic_2tuple_matrix": {
        "summary": "Basic linguistic 2-tuple TOPSIS request",
        "description": (
            "Executes 2-Tuple TOPSIS with two alternatives, "
            "two criteria, two weighted experts, linguistic "
            "2-tuple evaluations, criterion weights, and "
            "benefit/cost criterion types."
        ),
        "value": {
            "context": {
                "issue": {
                    "id": "issue-topsis-2tuple-001",
                    "name": "Linguistic supplier selection",
                    "consensusThreshold": None,
                    "consensusMaxPhases": None,
                },
                "alternatives": [
                    {
                        "id": "alt-a",
                        "name": "Alternative A",
                    },
                    {
                        "id": "alt-b",
                        "name": "Alternative B",
                    },
                ],
                "criteria": [
                    {
                        "id": "criterion-benefit",
                        "name": "Quality",
                        "type": "benefit",
                        "expressionDomain": (
                            LINGUISTIC_2TUPLE_DOMAIN
                        ),
                    },
                    {
                        "id": "criterion-cost",
                        "name": "Cost",
                        "type": "cost",
                        "expressionDomain": (
                            LINGUISTIC_2TUPLE_DOMAIN
                        ),
                    },
                ],
                "consensusPhase": 0,
                "previousStageResult": None,
                "structure": {
                    "key": "alternativeCriteriaMatrix",
                    "stage": "alternativeEvaluation",
                },
            },
            "modelParameters": {
                "weights": {
                    "criterion-benefit": 2.0,
                    "criterion-cost": 1.0,
                }
            },
            "evaluations": [
                {
                    "expert": {
                        "id": "expert-1",
                        "name": "Expert 1",
                        "email": "expert1@example.com",
                    },
                    "weight": 0.25,
                    "payload": {
                        "alt-a": {
                            "criterion-benefit": {
                                "labelKey": "s2",
                                "alpha": -0.25,
                            },
                            "criterion-cost": {
                                "labelKey": "s3",
                                "alpha": 0.0,
                            },
                        },
                        "alt-b": {
                            "criterion-benefit": {
                                "labelKey": "s4",
                                "alpha": -0.5,
                            },
                            "criterion-cost": {
                                "labelKey": "s1",
                                "alpha": 0.25,
                            },
                        },
                    },
                },
                {
                    "expert": {
                        "id": "expert-2",
                        "name": "Expert 2",
                        "email": "expert2@example.com",
                    },
                    "weight": 0.75,
                    "payload": {
                        "alt-a": {
                            "criterion-benefit": {
                                "labelKey": "s2",
                                "alpha": 0.0,
                            },
                            "criterion-cost": {
                                "labelKey": "s2",
                                "alpha": 0.25,
                            },
                        },
                        "alt-b": {
                            "criterion-benefit": {
                                "labelKey": "s3",
                                "alpha": 0.25,
                            },
                            "criterion-cost": {
                                "labelKey": "s1",
                                "alpha": 0.0,
                            },
                        },
                    },
                },
            ],
        },
    }
}


TOPSIS_2TUPLE_RESPONSE_EXAMPLES: dict[
    str,
    dict[str, Any],
] = {
    "success": {
        "summary": "Successful execution",
        "description": (
            "Successful 2-Tuple TOPSIS execution for the "
            "basic linguistic matrix request."
        ),
        "value": {
            "success": True,
            "message": "2-Tuple TOPSIS executed successfully",
            "data": {
                "rankedAlternatives": [
                    {
                        "alternativeId": "alt-b",
                        "name": "Alternative B",
                        "score": 1.0,
                        "rank": 1,
                    },
                    {
                        "alternativeId": "alt-a",
                        "name": "Alternative A",
                        "score": 0.0,
                        "rank": 2,
                    },
                ],
                "collectiveEvaluations": {
                    "alt-a": {
                        "criterion-benefit": {
                            "labelKey": "s2",
                            "alpha": -0.0625,
                        },
                        "criterion-cost": {
                            "labelKey": "s2",
                            "alpha": 0.4375,
                        },
                    },
                    "alt-b": {
                        "criterion-benefit": {
                            "labelKey": "s3",
                            "alpha": 0.3125,
                        },
                        "criterion-cost": {
                            "labelKey": "s1",
                            "alpha": 0.0625,
                        },
                    },
                },
                "plotsGraphic": {},
                "consensusMeasure": None,
                "rawOutput": {
                    "collective_beta_matrix": [
                        [1.9375, 2.4375],
                        [3.3125, 1.0625],
                    ],
                    "positive_ideal_beta": [
                        3.3125,
                        1.0625,
                    ],
                    "negative_ideal_beta": [
                        1.9375,
                        2.4375,
                    ],
                    "positive_distances": [
                        1.375,
                        0.0,
                    ],
                    "negative_distances": [
                        0.0,
                        1.375,
                    ],
                    "closeness_coefficients": [
                        0.0,
                        1.0,
                    ],
                    "collective_scores": [
                        0.0,
                        1.0,
                    ],
                    "collective_ranking": [
                        1,
                        0,
                    ],
                    "expert_weights": [
                        0.25,
                        0.75,
                    ],
                    "criterion_weights": [
                        2.0 / 3.0,
                        1.0 / 3.0,
                    ],
                    "criterion_directions": [
                        "max",
                        "min",
                    ],
                    "plots_graphic": {},
                },
            },
        },
    },
    "error": {
        "summary": "Execution error",
        "value": {
            "success": False,
            "message": "<validation or execution error>",
            "data": None,
            "error": {
                "code": "MODEL_EXECUTION_ERROR",
                "field": None,
                "details": None,
            },
        },
    },
}


__all__ = [
    "TOPSIS_2TUPLE_REQUEST_EXAMPLES",
    "TOPSIS_2TUPLE_RESPONSE_EXAMPLES",
]
