// Generated by ModelForge.
// Registers this Parameter Structure.
// See IMPLEMENTATION_GUIDE.md.

import { validateTwoTupleAggregationParameter } from "./validate.js";

export const twoTupleAggregationParameterStructure = Object.freeze({
  key: "twoTupleAggregation",
  implementationStatus: "ready",
  validateAndNormalize: validateTwoTupleAggregationParameter,
});
