// Generated by ModelForge.
// Validates and normalizes this Parameter Structure value.
// See IMPLEMENTATION_GUIDE.md.

import { isPlainObject } from "../../../../../utils/common/objects.js";
import { toInvalid, toValid } from "../../parameterValidationResult.js";

const METHODS = new Set(["arithmetic_mean", "weighted_average", "l2towa"]);
const PREDEFINED_QUANTIFIERS = new Set([
  "most",
  "at_least_half",
  "as_many_as_possible",
]);

export const validateTwoTupleAggregationParameter = ({
  value,
  parameter,
  context,
}) => {
  void parameter;
  void context;

  if (!isPlainObject(value)) {
    return toInvalid("must be an object with method and options", value);
  }

  const { method, options } = value;
  if (typeof method !== "string" || !METHODS.has(method)) {
    return toInvalid("must use a supported aggregation method", value);
  }
  if (!isPlainObject(options)) {
    return toInvalid("options must be an object", value);
  }

  if (method === "arithmetic_mean" || method === "weighted_average") {
    return toValid({ method, options: {} });
  }

  const { quantifier } = options;
  if (PREDEFINED_QUANTIFIERS.has(quantifier)) {
    return toValid({ method, options: { quantifier } });
  }
  if (quantifier !== "custom") {
    return toInvalid("l2towa options must include a supported quantifier", value);
  }

  const { a, b } = options;
  if (typeof a !== "number" || !Number.isFinite(a)) {
    return toInvalid("custom l2towa quantifier requires a finite numeric a", value);
  }
  if (typeof b !== "number" || !Number.isFinite(b)) {
    return toInvalid("custom l2towa quantifier requires a finite numeric b", value);
  }
  if (a < 0 || a >= b || b > 1) {
    return toInvalid("custom l2towa quantifier must satisfy 0 <= a < b <= 1", value);
  }

  return toValid({ method, options: { quantifier, a, b } });
};
