// Generated by ModelForge.
// Backend contract for this evaluation structure.
// get() returns the canonical payload shape consumed directly by the frontend View.
// save() receives the same payload shape and must validate and normalize it.
//
// Example evaluationContext:
// {
//   issue: {
//     id: "665f0b8f6f1e9c12a34b5600",
//     name: "Supplier selection 2026",
//     currentStage: "alternativeEvaluation",
//     consensusPhase: 0,
//     isConsensus: true,
//     consensusThreshold: 0.75,
//     consensusMaxPhases: 3,
//   },
//   structure: {
//     key: "sampleEvaluationStructure",
//     stage: "alternativeEvaluation",
//   },
//   model: {
//     id: "665f0b8f6f1e9c12a34b5690",
//     name: "Sample Scaffold Model",
//     apiModelKey: "sample_scaffold_model",
//   },
//   modelParameters: {
//     sample_param: 0.5,
//   },
//   criteriaWeightingParameters: {
//     eps_penalty: 1,
//   },
//   alternatives: [
//     { id: "665f0b8f6f1e9c12a34b5672", name: "Supplier A" },
//     { id: "665f0b8f6f1e9c12a34b5673", name: "Supplier B" },
//   ],
//   criteriaTree: [
//     {
//       id: "665f0b8f6f1e9c12a34b5679",
//       name: "Economic criteria",
//       type: null,
//       expressionDomain: null,
//       children: [
//         {
//           id: "665f0b8f6f1e9c12a34b5674",
//           name: "Cost",
//           type: "cost",
//           expressionDomain: {
//             id: "665f0b8f6f1e9c12a34b5701",
//             _id: "665f0b8f6f1e9c12a34b5701",
//             name: "Numeric 0-10",
//             type: "numeric",
//             numericRange: { min: 0, max: 10, step: 0.5 },
//             linguisticLabels: [],
//             membershipFunction: null,
//             valueCount: null,
//             valuesMode: null,
//           },
//           children: [],
//         },
//         {
//           id: "665f0b8f6f1e9c12a34b5675",
//           name: "Quality",
//           type: "benefit",
//           expressionDomain: {
//             id: "665f0b8f6f1e9c12a34b5702",
//             _id: "665f0b8f6f1e9c12a34b5702",
//             name: "Five linguistic labels",
//             type: "linguistic",
//             numericRange: { min: null, max: null, step: null },
//             linguisticLabels: [
//               { label: "Label 1", values: [0, 0, 0.25] },
//               { label: "Label 2", values: [0, 0.25, 0.5] },
//               { label: "Label 3", values: [0.25, 0.5, 0.75] },
//               { label: "Label 4", values: [0.5, 0.75, 1] },
//               { label: "Label 5", values: [0.75, 1, 1] },
//             ],
//             membershipFunction: "triangular",
//             valueCount: 3,
//             valuesMode: "automatic",
//           },
//           children: [],
//         },
//       ],
//     },
//   ],
//   leafCriteria: [
//     {
//       id: "665f0b8f6f1e9c12a34b5674",
//       name: "Cost",
//       type: "cost",
//       expressionDomain: {
//         id: "665f0b8f6f1e9c12a34b5701",
//         _id: "665f0b8f6f1e9c12a34b5701",
//         name: "Numeric 0-10",
//         type: "numeric",
//         numericRange: { min: 0, max: 10, step: 0.5 },
//         linguisticLabels: [],
//         membershipFunction: null,
//         valueCount: null,
//         valuesMode: null,
//       },
//     },
//     {
//       id: "665f0b8f6f1e9c12a34b5675",
//       name: "Quality",
//       type: "benefit",
//       expressionDomain: {
//         id: "665f0b8f6f1e9c12a34b5702",
//         _id: "665f0b8f6f1e9c12a34b5702",
//         name: "Five linguistic labels",
//         type: "linguistic",
//         numericRange: { min: null, max: null, step: null },
//         linguisticLabels: [
//           { label: "Label 1", values: [0, 0, 0.25] },
//           { label: "Label 2", values: [0, 0.25, 0.5] },
//           { label: "Label 3", values: [0.25, 0.5, 0.75] },
//           { label: "Label 4", values: [0.5, 0.75, 1] },
//           { label: "Label 5", values: [0.75, 1, 1] },
//         ],
//         membershipFunction: "triangular",
//         valueCount: 3,
//         valuesMode: "automatic",
//       },
//     },
//   ],
//   consensus: {
//     phase: 0,
//     maxPhases: 3,
//     threshold: 0.75,
//     currentCollectiveEvaluations: {},
//     previousCollectiveEvaluations: {},
//   },
// }

import {
  EVALUATION_STAGES,
} from "../../evaluationStages.js";
import { createBadRequestError } from "../../../../../utils/common/errors.js";

export const sampleEvaluationStructure = Object.freeze({
  key: "sampleEvaluationStructure",
  stage: EVALUATION_STAGES.ALTERNATIVE_EVALUATION,
  implementationStatus: "scaffold",

  async get({ payload }) {
    return payload ?? {};
  },

  async save({ payload, evaluationContext, mode }) {
    void payload;
    void evaluationContext;
    void mode;
    throw createBadRequestError(
      "Evaluation structure is under development",
      {
        code: "EVALUATION_STRUCTURE_UNDER_DEVELOPMENT",
        field: "payload",
      }
    );
  },
});
