// Generated by ModelForge.
// Registers the editable and read-only frontend components for this parameter structure.

import SampleParameterGlobalParameterField from "./SampleParameterGlobalParameterField";
import SampleParameterGlobalParameterReadOnly from "./SampleParameterGlobalParameterReadOnly";

export const sampleParameterGlobalParameterField = Object.freeze({
  key: "sampleParameterGlobal",
  implementationStatus: "scaffold",
  FieldComponent: SampleParameterGlobalParameterField,
  ReadOnlyComponent: SampleParameterGlobalParameterReadOnly,
});
