// Generated by ModelForge.
// ReadOnlyComponent displays this parameter value.
//
// Example parameterContext:
// {
//   model: {
//     id: "665f0b8f6f1e9c12a34b5690",
//     name: "Sample Scaffold Model",
//     apiModelKey: "sample_scaffold_model",
//   },
//   alternatives: [
//     { id: "665f0b8f6f1e9c12a34b5672", name: "Supplier A" },
//     { id: "665f0b8f6f1e9c12a34b5673", name: "Supplier B" },
//   ],
//   criteriaTree: [
//     {
//       id: "665f0b8f6f1e9c12a34b5679",
//       name: "Economic criteria",
//       type: null,
//       expressionDomain: null,
//       children: [
//         {
//           id: "665f0b8f6f1e9c12a34b5674",
//           name: "Cost",
//           type: "cost",
//           expressionDomain: {
//             id: "665f0b8f6f1e9c12a34b5701",
//             _id: "665f0b8f6f1e9c12a34b5701",
//             name: "Numeric 0-10",
//             type: "numeric",
//             numericRange: { min: 0, max: 10, step: 0.5 },
//             linguisticLabels: [],
//             membershipFunction: null,
//             valueCount: null,
//             valuesMode: null,
//           },
//           children: [],
//         },
//       ],
//     },
//   ],
//   leafCriteria: [
//     {
//       id: "665f0b8f6f1e9c12a34b5674",
//       name: "Cost",
//       type: "cost",
//       expressionDomain: {
//         id: "665f0b8f6f1e9c12a34b5701",
//         _id: "665f0b8f6f1e9c12a34b5701",
//         name: "Numeric 0-10",
//         type: "numeric",
//         numericRange: { min: 0, max: 10, step: 0.5 },
//         linguisticLabels: [],
//         membershipFunction: null,
//         valueCount: null,
//         valuesMode: null,
//       },
//     },
//   ],
// }

import { Stack, Typography } from "@mui/material";

export const SampleParameterGlobalParameterReadOnly = ({
  parameter,
  value,
  parameterContext,
}) => {
  void parameterContext;

  return (
    <Stack spacing={0.35}>
      <Typography variant="body2" sx={{ fontWeight: 700 }}>
        {parameter.label}
      </Typography>

      <Typography
        variant="body2"
        component="pre"
        sx={{
          m: 0,
          fontFamily: "monospace",
          whiteSpace: "pre-wrap",
          wordBreak: "break-word",
        }}
      >
        {JSON.stringify(value ?? null, null, 2)}
      </Typography>
    </Stack>
  );
};

export default SampleParameterGlobalParameterReadOnly;
