// Generated by ModelForge.
// Validates and normalizes this Evaluation Structure payload before persistence.
// See IMPLEMENTATION_GUIDE.md.

import {
  normalizeCriteriaPreferenceOrderPayload,
} from "./operations/normalizePayload.js";
import {
  validateCriteriaPreferenceOrderPayloadOrThrow,
} from "./operations/validatePayload.js";

export const saveCriteriaPreferenceOrderPayload = async ({
  payload,
  decisionContext,
  mode,
}) => {
  validateCriteriaPreferenceOrderPayloadOrThrow({
    payload,
    decisionContext,
    mode,
  });

  return normalizeCriteriaPreferenceOrderPayload({
    payload,
  });
};