// Generated by ModelForge.
// Prepares this Evaluation Structure payload for the Frontend.
// See IMPLEMENTATION_GUIDE.md.

export const getCriteriaPreferenceOrderPayload = async ({
  payload,
  decisionContext,
}) => {
  void decisionContext;

  return payload ?? {};
};
