// Generated by ModelForge.
// Prepares this Evaluation Structure payload for the Frontend.
// See IMPLEMENTATION_GUIDE.md.

import {
  normalizeCriteriaPreferenceOrderPayload,
} from "./operations/normalizePayload.js";
import {
  validateCriteriaPreferenceOrderPayloadOrThrow,
} from "./operations/validatePayload.js";

export const getCriteriaPreferenceOrderPayload = async ({
  payload,
  decisionContext,
}) => {
  if (payload == null) {
    return {
      criterionOrder: [],
    };
  }

  validateCriteriaPreferenceOrderPayloadOrThrow({
    payload,
    decisionContext,
    mode: "draft",
  });

  return normalizeCriteriaPreferenceOrderPayload({
    payload,
  });
};