// Generated by ModelForge.
// Prepares this Evaluation Structure payload for the Frontend.
// See IMPLEMENTATION_GUIDE.md.

import { normalizePayload } from "./operations/normalizePayload.js";
import { resolveCriteria } from "./operations/resolveCriteria.js";

export const getCriteriaPreferenceOrderPayload = async ({
  payload,
  decisionContext,
}) => {
  if (payload === null || payload === undefined) {
    resolveCriteria({ decisionContext });

    return {
      criterionOrder: [],
    };
  }

  return normalizePayload({
    payload,
    decisionContext,
    requireValue: false,
  });
};