// Generated by ModelForge.
// Validates and normalizes this Evaluation Structure payload before persistence.
// See IMPLEMENTATION_GUIDE.md.

export const saveCriteriaPreferenceOrderPayload = async ({
  payload,
  decisionContext,
  mode,
}) => {
  void decisionContext;
  void mode;

  return payload;
};
