// Generated by ModelForge.
// Validates and normalizes this Evaluation Structure payload before persistence.
// See IMPLEMENTATION_GUIDE.md.

import { resolveRequireValue } from "../../shared/resolveRequireValue.js";
import { normalizePayload } from "./operations/normalizePayload.js";

export const saveCriteriaPreferenceOrderPayload = async ({
  payload,
  decisionContext,
  mode,
}) => {
  const requireValue = resolveRequireValue(mode);

  return normalizePayload({
    payload,
    decisionContext,
    requireValue,
  });
};