// Generated by ModelForge.
// Registers this Evaluation Structure.
// See IMPLEMENTATION_GUIDE.md.

import { EVALUATION_STAGES } from "../../evaluationStages.js";
import { getCriteriaPreferenceOrderPayload } from "./criteriaPreferenceOrder.get.js";
import { saveCriteriaPreferenceOrderPayload } from "./criteriaPreferenceOrder.save.js";
import {
  remapCriteriaPreferenceOrderCriterionIds,
} from "./operations/remapCriterionIds.js";

export const criteriaPreferenceOrder = Object.freeze({
  key: "criteriaPreferenceOrder",
  stage: EVALUATION_STAGES.CRITERIA_WEIGHTING,
  implementationStatus: "ready",
  get: getCriteriaPreferenceOrderPayload,
  save: saveCriteriaPreferenceOrderPayload,
  remapCriterionIds: remapCriteriaPreferenceOrderCriterionIds,
});