import { Box, Chip, Stack, Typography } from "@mui/material";
import TuneRoundedIcon from "@mui/icons-material/TuneRounded";
import { ExpressionDomainPreview } from "../../../../createIssue/expressionDomains/components/ExpressionDomainPreview.jsx";
import { evaluationsPanelHeaderSx, evaluationsPanelSx } from "../evaluations.styles";

const ExpressionDomainsPanel = ({ domains }) => <Box sx={evaluationsPanelSx}>
  <Box sx={evaluationsPanelHeaderSx}><TuneRoundedIcon sx={{ color: "secondary.light", fontSize: 21 }} /><Box sx={{ minWidth: 0 }}><Typography variant="h6" component="h2">Expression domains by criterion</Typography><Typography variant="caption" sx={{ color: "text.secondary" }}>Stored domains used to express each leaf criterion.</Typography></Box><Chip size="small" variant="outlined" color="secondary" label={domains.length} sx={{ ml: "auto", height: 24, fontWeight: 850 }} /></Box>
  {domains.length ? <Box sx={{ display: "grid", gridTemplateColumns: { xs: "minmax(0, 1fr)", md: "repeat(2, minmax(0, 1fr))" }, gap: 1 }} aria-label="Expression domains by criterion">{domains.map((item) => <Box key={item.criterionId} sx={{ minWidth: 0, p: 1.1, border: "1px solid rgba(255,255,255,0.08)", borderRadius: 2, bgcolor: "rgba(3,10,17,0.26)" }}><Stack direction="row" spacing={0.7} alignItems="center" justifyContent="space-between"><Typography variant="body2" noWrap title={item.name} sx={{ fontWeight: "fontWeightBold", minWidth: 0 }}>{item.name}</Typography><Chip size="small" variant="outlined" color={item.domainScope === "owner" ? "info" : "default"} label={item.domainScope === "owner" ? "Owner" : "Global"} sx={{ height: 22, flexShrink: 0 }} /></Stack><Typography variant="subtitle2" noWrap title={item.domainName} sx={{ color: "secondary.light", fontWeight: "fontWeightBold", mt: 0.45 }}>{item.domainName}</Typography><Typography variant="caption" sx={{ display: "block", color: "text.secondary", mt: 0.25 }}>{item.domainDisplayMeta?.descriptor || item.domainTypeLabel || "—"}</Typography>{item.domain ? <Box sx={{ mt: 0.85, minWidth: 0 }}><ExpressionDomainPreview domain={item.domain} /></Box> : null}</Box>)}</Box> : <Typography variant="body2" color="text.secondary">No criterion domain assignments are available.</Typography>}
</Box>;
export default ExpressionDomainsPanel;
