from pathlib import Path


def _build_payload() -> dict[str, object]:
    return {
        "expressionDomainType": {
            "typeKey": "customPreferenceScale",
            "label": "Custom preference scale",
            "description": "Generated scaffold for a custom preference scale expression domain type.",
            "family": "custom",
            "constraintExample": {
                "alpha": {
                    "min": -0.5,
                    "max": 0.5,
                }
            },
            "definitionExample": {
                "levels": [
                    {"key": "low", "label": "Low"},
                    {"key": "high", "label": "High"},
                ]
            },
            "evaluationExample": {"levelKey": "low"},
        }
    }


def test_expression_domain_type_preview_reports_expected_files(
    client_factory,
    project_root: Path,
) -> None:
    payload = _build_payload()

    with client_factory(project_root) as client:
        response = client.post("/scaffold/expression-domain-type/preview", json=payload)

    assert response.status_code == 200
    body = response.json()
    assert body["service"] == "model-forge"
    assert body["kind"] == "expression-domain-type"
    assert body["mode"] == "preview"
    assert body["backendTargetBasePath"] == (
        "Backend/modules/decisionPlugins/expressionDomains/types/customPreferenceScale"
    )
    assert body["frontendTargetBasePath"] == (
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale"
    )

    item = body["items"][0]
    assert item["kind"] == "expression-domain-type"
    assert item["key"] == "customPreferenceScale"
    assert item["status"] == "toGenerate"

    preview_paths = [file["path"] for file in item["files"]]
    assert preview_paths == [
        "Backend/modules/decisionPlugins/expressionDomains/types/customPreferenceScale/index.js",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/index.js",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/CustomPreferenceScaleCreationForm.jsx",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/CustomPreferenceScaleEvaluationInput.jsx",
    ]

    files_by_path = {file["path"]: file["content"] for file in item["files"]}
    backend_source = files_by_path[
        "Backend/modules/decisionPlugins/expressionDomains/types/customPreferenceScale/index.js"
    ]
    frontend_index_source = files_by_path[
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/index.js"
    ]
    creation_form_source = files_by_path[
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/CustomPreferenceScaleCreationForm.jsx"
    ]
    evaluation_input_source = files_by_path[
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/CustomPreferenceScaleEvaluationInput.jsx"
    ]

    assert "Generated by ModelForge." in backend_source
    assert "EXPRESSION_DOMAIN_TYPE_UNDER_DEVELOPMENT" in backend_source
    assert "isPlainObject" not in backend_source
    assert "normalizeDefinitionOrThrow" not in backend_source
    assert 'validateEvaluation({ value, expressionDomain } = {})' in backend_source
    assert "field" not in backend_source
    assert "Generated by ModelForge." in frontend_index_source
    assert "constraintExample" in frontend_index_source
    assert "export const" in frontend_index_source
    assert "  constraintExample: {\n    alpha: {\n      min: -0.5,\n      max: 0.5,\n    },\n  }," in frontend_index_source
    assert '"alpha"' not in frontend_index_source
    assert "Generated by ModelForge." in creation_form_source
    assert "buildDraft" in creation_form_source
    assert "patch" not in creation_form_source
    assert "Definition JSON" not in creation_form_source
    assert "useState" not in creation_form_source
    assert "useEffect" not in creation_form_source
    assert "JSON.parse" not in creation_form_source
    assert 'const DEFAULT_DEFINITION = {' in creation_form_source
    assert '  levels: [' in creation_form_source
    assert '      key: "low",' in creation_form_source
    assert "Generated by ModelForge." in evaluation_input_source
    assert "Value JSON" not in evaluation_input_source
    assert "TextField" not in evaluation_input_source
    assert "useState" not in evaluation_input_source
    assert "useEffect" not in evaluation_input_source
    assert "JSON.stringify" not in evaluation_input_source
    assert "JSON.parse" not in evaluation_input_source
    assert "export const" in evaluation_input_source


def test_expression_domain_type_apply_writes_global_plugin_files(
    client_factory,
    project_root: Path,
) -> None:
    payload = _build_payload() | {"runFullFrontendBuild": False}

    with client_factory(project_root) as client:
        response = client.post("/scaffold/expression-domain-type/apply", json=payload)

    assert response.status_code == 200
    body = response.json()
    assert body["kind"] == "expression-domain-type"
    assert body["mode"] == "apply"

    item = body["items"][0]
    assert item["status"] == "written"
    written_paths = [file["path"] for file in item["writtenFiles"]]
    assert written_paths == [
        "Backend/modules/decisionPlugins/expressionDomains/types/customPreferenceScale/index.js",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/index.js",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/CustomPreferenceScaleCreationForm.jsx",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/CustomPreferenceScaleEvaluationInput.jsx",
    ]

    for relative_path in written_paths:
        assert (project_root / relative_path).exists()

    backend_source = (
        project_root
        / "Backend/modules/decisionPlugins/expressionDomains/types/customPreferenceScale/index.js"
    ).read_text(encoding="utf-8")
    creation_form_source = (
        project_root
        / "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/CustomPreferenceScaleCreationForm.jsx"
    ).read_text(encoding="utf-8")
    evaluation_input_source = (
        project_root
        / "Frontend/src/features/decisionPlugins/expressionDomains/types/customPreferenceScale/CustomPreferenceScaleEvaluationInput.jsx"
    ).read_text(encoding="utf-8")

    assert "Generated by ModelForge." in backend_source
    assert "EXPRESSION_DOMAIN_TYPE_UNDER_DEVELOPMENT" in backend_source
    assert "isPlainObject" not in backend_source
    assert 'validateEvaluation({ value, expressionDomain } = {})' in backend_source
    assert "field" not in backend_source
    assert "Definition JSON" not in creation_form_source
    assert "patch" not in creation_form_source
    assert 'const DEFAULT_DEFINITION = {' in creation_form_source
    assert "Value JSON" not in evaluation_input_source
    assert "TextField" not in evaluation_input_source


def test_expression_domain_type_preview_rejects_core_type_key(
    client_factory,
    project_root: Path,
) -> None:
    payload = _build_payload()
    payload["expressionDomainType"]["typeKey"] = "numericContinuous"

    with client_factory(project_root) as client:
        response = client.post("/scaffold/expression-domain-type/preview", json=payload)

    assert response.status_code == 422
    detail = response.json()["detail"]
    assert detail[0]["loc"][-1] == "typeKey"
