from pathlib import Path


def _build_payload() -> dict[str, object]:
    return {
        "expressionDomainType": {
            "typeKey": "linguisticTwoTupleScale",
            "label": "Linguistic 2-tuple scale",
            "description": "Generated scaffold for a linguistic 2-tuple-inspired expression domain type.",
            "family": "linguistic",
            "constraintExample": {
                "labelCount": [3, 5, 7]
            },
            "definitionExample": {
                "labelCount": 3,
                "alphaRange": {
                    "min": -0.5,
                    "max": 0.5,
                },
                "labels": [
                    {"key": "low", "label": "Low", "index": 0},
                    {"key": "medium", "label": "Medium", "index": 1},
                    {"key": "high", "label": "High", "index": 2},
                ]
            },
            "evaluationExample": {"labelKey": "high"},
        }
    }


def test_expression_domain_type_preview_reports_expected_files(
    client_factory,
    project_root: Path,
) -> None:
    payload = _build_payload()

    with client_factory(project_root) as client:
        response = client.post("/scaffold/expression-domain-type/preview", json=payload)

    assert response.status_code == 200
    body = response.json()
    assert body["service"] == "model-forge"
    assert body["kind"] == "expression-domain-type"
    assert body["mode"] == "preview"
    assert body["backendTargetBasePath"] == (
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale"
    )
    assert body["frontendTargetBasePath"] == (
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale"
    )

    item = body["items"][0]
    assert item["kind"] == "expression-domain-type"
    assert item["key"] == "linguisticTwoTupleScale"
    assert item["status"] == "toGenerate"

    preview_paths = [file["path"] for file in item["files"]]
    assert preview_paths == [
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/index.js",
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/creation.js",
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/evaluation.js",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/index.js",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/LinguisticTwoTupleScaleCreationForm.jsx",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/LinguisticTwoTupleScaleEvaluationInput.jsx",
    ]

    files_by_path = {file["path"]: file["content"] for file in item["files"]}
    backend_index_source = files_by_path[
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/index.js"
    ]
    backend_creation_source = files_by_path[
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/creation.js"
    ]
    backend_evaluation_source = files_by_path[
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/evaluation.js"
    ]
    frontend_index_source = files_by_path[
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/index.js"
    ]
    creation_form_source = files_by_path[
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/LinguisticTwoTupleScaleCreationForm.jsx"
    ]
    evaluation_input_source = files_by_path[
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/LinguisticTwoTupleScaleEvaluationInput.jsx"
    ]

    assert "Generated by ModelForge." in backend_index_source
    assert (
        'import { normalizeExpressionDomainNameOrThrow } from "../../shared/validation.js";'
        in backend_index_source
    )
    assert 'from "./creation.js";' in backend_index_source
    assert 'from "./evaluation.js";' in backend_index_source
    assert "normalizeLinguisticTwoTupleScaleCreationDefinition" in backend_index_source
    assert "normalizeLinguisticTwoTupleScaleEvaluationValue" in backend_index_source
    assert 'validateEvaluation({ value, expressionDomain } = {})' in backend_index_source
    assert "EXPRESSION_DOMAIN_TYPE_UNDER_DEVELOPMENT" in backend_creation_source
    assert "EXPRESSION_DOMAIN_TYPE_UNDER_DEVELOPMENT" in backend_evaluation_source
    assert "definitionExample from ModelForge is only guidance for implementers." in backend_creation_source
    assert "evaluationExample from ModelForge is only guidance for implementers." in backend_evaluation_source
    assert 'field: "definition"' in backend_creation_source
    assert "field" not in backend_evaluation_source
    assert "Generated by ModelForge." in frontend_index_source
    assert "constraintExample" in frontend_index_source
    assert "export const" in frontend_index_source
    assert "  constraintExample: {\n    labelCount: [\n      3,\n      5,\n      7,\n    ],\n  }," in frontend_index_source
    assert '"labelCount"' not in frontend_index_source
    assert "Generated by ModelForge." in creation_form_source
    assert "buildDraft" in creation_form_source
    assert "patch" not in creation_form_source
    assert "Definition JSON" not in creation_form_source
    assert "useState" not in creation_form_source
    assert "useEffect" not in creation_form_source
    assert "JSON.parse" not in creation_form_source
    assert 'const DEFAULT_DEFINITION = {' in creation_form_source
    assert '  levels: [' in creation_form_source
    assert '      key: "low",' in creation_form_source
    assert "Generated by ModelForge." in evaluation_input_source
    assert "Value JSON" not in evaluation_input_source
    assert "TextField" not in evaluation_input_source
    assert "useState" not in evaluation_input_source
    assert "useEffect" not in evaluation_input_source
    assert "JSON.stringify" not in evaluation_input_source
    assert "JSON.parse" not in evaluation_input_source
    assert "export const" in evaluation_input_source


def test_expression_domain_type_apply_writes_global_plugin_files(
    client_factory,
    project_root: Path,
) -> None:
    payload = _build_payload() | {"runFullFrontendBuild": False}

    with client_factory(project_root) as client:
        response = client.post("/scaffold/expression-domain-type/apply", json=payload)

    assert response.status_code == 200
    body = response.json()
    assert body["kind"] == "expression-domain-type"
    assert body["mode"] == "apply"

    item = body["items"][0]
    assert item["status"] == "written"
    written_paths = [file["path"] for file in item["writtenFiles"]]
    assert written_paths == [
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/index.js",
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/creation.js",
        "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/evaluation.js",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/index.js",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/LinguisticTwoTupleScaleCreationForm.jsx",
        "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/LinguisticTwoTupleScaleEvaluationInput.jsx",
    ]

    for relative_path in written_paths:
        assert (project_root / relative_path).exists()

    backend_index_source = (
        project_root
        / "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/index.js"
    ).read_text(encoding="utf-8")
    backend_creation_source = (
        project_root
        / "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/creation.js"
    ).read_text(encoding="utf-8")
    backend_evaluation_source = (
        project_root
        / "Backend/modules/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/evaluation.js"
    ).read_text(encoding="utf-8")
    creation_form_source = (
        project_root
        / "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/LinguisticTwoTupleScaleCreationForm.jsx"
    ).read_text(encoding="utf-8")
    evaluation_input_source = (
        project_root
        / "Frontend/src/features/decisionPlugins/expressionDomains/types/linguisticTwoTupleScale/LinguisticTwoTupleScaleEvaluationInput.jsx"
    ).read_text(encoding="utf-8")

    assert "Generated by ModelForge." in backend_index_source
    assert 'from "./creation.js";' in backend_index_source
    assert 'from "./evaluation.js";' in backend_index_source
    assert "EXPRESSION_DOMAIN_TYPE_UNDER_DEVELOPMENT" in backend_creation_source
    assert "EXPRESSION_DOMAIN_TYPE_UNDER_DEVELOPMENT" in backend_evaluation_source
    assert "Implement creation.js before using this type." in backend_creation_source
    assert "Implement evaluation.js before using this type." in backend_evaluation_source
    assert "Definition JSON" not in creation_form_source
    assert "patch" not in creation_form_source
    assert 'const DEFAULT_DEFINITION = {' in creation_form_source
    assert "Value JSON" not in evaluation_input_source
    assert "TextField" not in evaluation_input_source


def test_expression_domain_type_preview_rejects_core_type_key(
    client_factory,
    project_root: Path,
) -> None:
    payload = _build_payload()
    payload["expressionDomainType"]["typeKey"] = "numericContinuous"

    with client_factory(project_root) as client:
        response = client.post("/scaffold/expression-domain-type/preview", json=payload)

    assert response.status_code == 422
    detail = response.json()["detail"]
    assert detail[0]["loc"][-1] == "typeKey"
