// Generated by ModelForge.
// Builds the complete creator-side initial payload for this Evaluation Structure.
// See IMPLEMENTATION_GUIDE.md.

import { resolveCriteria } from "./resolveCriteria";

export const buildInitialEvaluation = ({ decisionContext }) => {
  resolveCriteria({ decisionContext });

  return {
    criterionOrder: [],
  };
};