// Generated by ModelForge.
// Builds the complete creator-side initial payload for this Evaluation Structure.
// See IMPLEMENTATION_GUIDE.md.

export const buildInitialEvaluation = ({ decisionContext }) => {
  void decisionContext;

  throw new Error(
    "criteriaPreferenceOrder buildInitialEvaluation must be implemented before creator-side use."
  );
};
