// Generated by ModelForge.
// Remaps creator-side temporary criterion IDs owned by this payload.
// See IMPLEMENTATION_GUIDE.md.

import {
  assertCriteriaPreferenceOrderPayloadShapeOrThrow,
} from "./validatePayload.js";

const isNonEmptyString = (value) => (
  typeof value === "string"
  && value.trim().length > 0
);

export const remapCriteriaPreferenceOrderCriterionIds = ({
  payload,
  criterionIdMap,
}) => {
  const criterionOrder = assertCriteriaPreferenceOrderPayloadShapeOrThrow(
    payload,
  );

  if (!(criterionIdMap instanceof Map)) {
    throw new TypeError(
      "criteriaPreferenceOrder criterionIdMap must be a Map.",
    );
  }

  const remappedCriterionOrder = criterionOrder.map(
    (sourceCriterionId) => {
      if (!criterionIdMap.has(sourceCriterionId)) {
        throw new Error(
          `criteriaPreferenceOrder cannot remap criterion ID "${sourceCriterionId}" because no mapping exists.`,
        );
      }

      const persistedCriterionId = criterionIdMap.get(sourceCriterionId);

      if (!isNonEmptyString(persistedCriterionId)) {
        throw new Error(
          `criteriaPreferenceOrder criterion ID "${sourceCriterionId}" maps to an invalid persisted criterion ID.`,
        );
      }

      return persistedCriterionId;
    },
  );

  const seenPersistedCriterionIds = new Set();

  for (const persistedCriterionId of remappedCriterionOrder) {
    if (seenPersistedCriterionIds.has(persistedCriterionId)) {
      throw new Error(
        `criteriaPreferenceOrder remapping produced duplicate persisted criterion ID "${persistedCriterionId}".`,
      );
    }

    seenPersistedCriterionIds.add(persistedCriterionId);
  }

  return {
    criterionOrder: remappedCriterionOrder,
  };
};