// Generated by ModelForge.
// Remaps creator-side temporary criterion IDs owned by this payload.
// See IMPLEMENTATION_GUIDE.md.

export const remapCriteriaPreferenceOrderCriterionIds = ({
  payload,
  criterionIdMap,
}) => {
  void payload;
  void criterionIdMap;

  throw new Error(
    "criteriaPreferenceOrder remapCriterionIds must be implemented before creator-side use."
  );
};
