// Generated by ModelForge.
// Remaps creator-side temporary criterion IDs owned by this payload.
// See IMPLEMENTATION_GUIDE.md.

import { createBadRequestError } from "../../../../../../utils/common/errors.js";
import {
  hasOwnKey,
  isPlainObject,
} from "../../../../../../utils/common/objects.js";
import { normalizeNonEmptyString } from "../../../../../../utils/common/strings.js";

export const remapCriteriaPreferenceOrderCriterionIds = ({
  payload,
  criterionIdMap,
}) => {
  if (!isPlainObject(payload)) {
    throw createBadRequestError(
      "criteriaPreferenceOrder payload must be an object",
      {
        field: "payload",
      }
    );
  }

  if (!(criterionIdMap instanceof Map)) {
    throw createBadRequestError("criterionIdMap must be a Map", {
      field: "criterionIdMap",
    });
  }

  if (!hasOwnKey(payload, "criterionOrder")) {
    throw createBadRequestError(
      "criteriaPreferenceOrder criterionOrder is required",
      {
        field: "payload.criterionOrder",
      }
    );
  }

  if (!Array.isArray(payload.criterionOrder)) {
    throw createBadRequestError(
      "criteriaPreferenceOrder criterionOrder must be an array",
      {
        field: "payload.criterionOrder",
      }
    );
  }

  const seenSourceCriterionIds = new Set();
  const seenMappedCriterionIds = new Set();

  const criterionOrder = payload.criterionOrder.map((criterionId, index) => {
    const field = `payload.criterionOrder[${index}]`;
    const normalizedCriterionId = normalizeNonEmptyString(criterionId);

    if (!normalizedCriterionId) {
      throw createBadRequestError(
        "criteriaPreferenceOrder criterion id must be a non-empty string",
        {
          field,
        }
      );
    }

    if (seenSourceCriterionIds.has(normalizedCriterionId)) {
      throw createBadRequestError(
        "criteriaPreferenceOrder criterion ids must be unique",
        {
          field,
          details: {
            criterionId: normalizedCriterionId,
          },
        }
      );
    }

    seenSourceCriterionIds.add(normalizedCriterionId);

    if (!criterionIdMap.has(normalizedCriterionId)) {
      throw createBadRequestError(
        "Unable to remap criteriaPreferenceOrder payload to persisted criteria",
        {
          field,
          details: {
            criterionId: normalizedCriterionId,
          },
        }
      );
    }

    const mappedCriterionId = normalizeNonEmptyString(
      criterionIdMap.get(normalizedCriterionId)
    );

    if (!mappedCriterionId) {
      throw createBadRequestError(
        "Mapped criterion id must be a non-empty string",
        {
          field,
          details: {
            criterionId: normalizedCriterionId,
          },
        }
      );
    }

    if (seenMappedCriterionIds.has(mappedCriterionId)) {
      throw createBadRequestError(
        "Remapped criteriaPreferenceOrder criterion ids must be unique",
        {
          field,
          details: {
            criterionId: normalizedCriterionId,
            mappedCriterionId,
          },
        }
      );
    }

    seenMappedCriterionIds.add(mappedCriterionId);

    return mappedCriterionId;
  });

  return {
    criterionOrder,
  };
};