import { Alternative } from "../../../models/Alternatives.js";
import { Criterion } from "../../../models/Criteria.js";
import { IssueEvaluation } from "../../../models/IssueEvaluations.js";
import { IssueExpressionDomain } from "../../../models/IssueExpressionDomains.js";
import { IssueModel } from "../../../models/IssueModels.js";
import { IssueStageResult } from "../../../models/IssueStageResults.js";
import { IssueStateSnapshot } from "../../../models/IssueStateSnapshots.js";
import { Participation } from "../../../models/Participations.js";
import { User } from "../../../models/Users.js";
import { toIdString } from "../../../utils/common/ids.js";

const clone = (value, field) => { try { return JSON.parse(JSON.stringify(value)); } catch { throw new TypeError(`${field} must be JSON-compatible`); } };
const iso = (value) => value instanceof Date ? value.toISOString() : value ?? null;
const q = (query, session) => session ? query.session(session) : query;
const modelSnapshot = (doc) => doc ? { id: toIdString(doc._id), name: doc.name, apiModelKey: doc.apiModelKey, modelKind: doc.modelKind, apiEndpoint: clone(doc.apiEndpoint ?? null, "model.apiEndpoint"), evaluationStructureKey: doc.evaluationStructureKey ?? null, supportsConsensus: doc.supportsConsensus === true, supportsConsensusSimulation: doc.supportsConsensusSimulation === true, usesCriteriaWeights: doc.usesCriteriaWeights === true, usesExpertWeights: doc.usesExpertWeights === true, usesFuzzyCriteriaWeights: doc.usesFuzzyCriteriaWeights === true, usesCriterionTypes: doc.usesCriterionTypes === true, supportedExpressionDomains: clone(doc.supportedExpressionDomains ?? [], "model.supportedExpressionDomains"), parameters: clone(doc.parameters ?? [], "model.parameters"), request: clone(doc.request ?? null, "model.request"), response: clone(doc.response ?? null, "model.response"), implementationStatus: doc.implementationStatus ?? null } : null;
export const buildIssueStateSnapshot = async ({ issue, consensusPhase = issue.consensusPhase, session = null }) => {
  const [model, criteriaWeightingModel, alternatives, criteria, domains, participations, evaluations, previousStageResult] = await Promise.all([
    q(IssueModel.findById(issue.model).lean(), session), q(IssueModel.findById(issue.criteriaWeightingModel).lean(), session), q(Alternative.find({ issue: issue._id }).sort({ position: 1, _id: 1 }).lean(), session), q(Criterion.find({ issue: issue._id }).sort({ parentCriterion: 1, position: 1, _id: 1 }).lean(), session), q(IssueExpressionDomain.find({ issue: issue._id }).sort({ _id: 1 }).lean(), session), q(Participation.find({ issue: issue._id }).sort({ expert: 1, _id: 1 }).lean(), session), q(IssueEvaluation.find({ issue: issue._id, consensusPhase }).sort({ expert: 1, _id: 1 }).lean(), session), consensusPhase > 0 ? q(IssueStageResult.findOne({ issue: issue._id, stage: "alternativeEvaluation", consensusPhase: consensusPhase - 1 }).lean(), session) : null,
  ]);
  const users = await q(User.find({ _id: { $in: participations.map((p) => p.expert) } }).select("name email university").lean(), session);
  const usersById = new Map(users.map((user) => [toIdString(user._id), user]));
  return clone({
    issue: { id: toIdString(issue._id), name: issue.name, description: issue.description, ownerId: toIdString(issue.ownerId), createdBy: toIdString(issue.createdBy), creationDate: issue.creationDate ?? null, closureDate: issue.closureDate ?? null, active: issue.active === true, currentStage: issue.currentStage, consensusPhase, isConsensus: issue.isConsensus === true, supportsConsensus: issue.supportsConsensus === true, simulateConsensus: issue.simulateConsensus === true, consensusThreshold: issue.consensusThreshold ?? null, consensusMaxPhases: issue.consensusMaxPhases ?? null, evaluationStructureKey: issue.evaluationStructureKey, effectiveModelParameters: clone(issue.modelParameters ?? {}, "issue.modelParameters") },
    model: modelSnapshot(model),
    criteriaWeighting: { required: issue.criteriaWeightsStructureKey != null, structureKey: issue.criteriaWeightsStructureKey ?? null, model: modelSnapshot(criteriaWeightingModel), apiModelKey: issue.criteriaWeightingApiModelKey ?? null, apiEndpoint: clone(issue.criteriaWeightingApiEndpoint ?? null, "criteriaWeighting.apiEndpoint"), parameters: clone(issue.criteriaWeightingParameters ?? {}, "criteriaWeighting.parameters"), weightsByCriterionId: clone(issue.modelParameters?.weights ?? {}, "criteriaWeighting.weights") },
    alternatives: alternatives.map((a) => ({ id: toIdString(a._id), name: a.name, description: a.description ?? null, position: a.position })),
    criteria: criteria.map((c) => ({ id: toIdString(c._id), parentCriterionId: toIdString(c.parentCriterion) || null, name: c.name, description: c.description ?? null, type: c.type, isLeaf: c.isLeaf === true, expressionDomainId: toIdString(c.expressionDomain) || null, position: c.position })),
    expressionDomains: domains.map((d) => ({ id: toIdString(d._id), sourceDomainId: toIdString(d.sourceDomain), name: d.name, typeKey: d.typeKey, definition: clone(d.definition ?? {}, "expressionDomain.definition") })),
    participants: participations.map((p) => { const user = usersById.get(toIdString(p.expert)); return { participationId: toIdString(p._id), expert: { id: toIdString(p.expert), name: user?.name ?? null, email: user?.email ?? null, university: user?.university ?? null }, invitationStatus: p.invitationStatus, evaluationCompleted: p.evaluationCompleted === true, weightsCompleted: p.weightsCompleted === true, weight: p.weight ?? null, entryStage: p.entryStage ?? null, entryPhase: p.entryPhase ?? null, joinedAt: iso(p.joinedAt) }; }),
    evaluations: evaluations.map((e) => ({ evaluationId: toIdString(e._id), expertId: toIdString(e.expert), stage: e.stage, consensusPhase: e.consensusPhase, payload: clone(e.payload ?? {}, "evaluation.payload"), completed: e.completed === true, submittedAt: iso(e.submittedAt) })),
    previousPhase: previousStageResult ? { phase: consensusPhase - 1, stageResultId: toIdString(previousStageResult._id), executionAttemptId: toIdString(previousStageResult.executionAttempt) || null, consensusMeasure: previousStageResult.result?.standardResult?.consensusMeasure ?? null, collectiveEvaluations: clone(previousStageResult.result?.standardResult?.collectiveEvaluations ?? null, "previousPhase.collectiveEvaluations"), rankedAlternatives: clone(previousStageResult.result?.standardResult?.rankedAlternatives ?? null, "previousPhase.rankedAlternatives"), modelExecution: clone(previousStageResult.result?.modelExecution ?? null, "previousPhase.modelExecution") } : null,
  }, "snapshot.state");
};
export const writeIssueStateSnapshot = async ({ issue, snapshotType, occurredAt, correlationId, sourceEvent = null, sourceExecutionAttempt = null, consensusPhase = issue.consensusPhase, session = null }) => IssueStateSnapshot.create([{ issue: issue._id, snapshotType, stage: issue.currentStage, consensusPhase, occurredAt, correlationId, sourceEvent, sourceExecutionAttempt, state: await buildIssueStateSnapshot({ issue, consensusPhase, session }), schemaVersion: 1 }], { session }).then(([snapshot]) => snapshot);
