import { performance } from "node:perf_hooks";
import axios from "axios";
import { IssueExecutionAttempt } from "../../../models/IssueExecutionAttempts.js";
import { createModelApiRequestError, unwrapModelApiResponse } from "../../../services/modelApi/modelResponse.js";
import { writeIssueEvent, ISSUE_EVENT_TYPES } from "../events/index.js";

const clone = (value, fallback = null) => { try { return value === undefined ? fallback : JSON.parse(JSON.stringify(value)); } catch { return fallback; } };
export const serializeExecutionError = (error) => ({ name: error?.name || "Error", message: error?.message || String(error), code: error?.code ?? null, status: error?.status ?? error?.statusCode ?? error?.response?.status ?? null, field: error?.field ?? null, details: clone(error?.details), responseBody: clone(error?.response?.data) });
const safeHeaders = (headers) => Object.fromEntries(Object.entries(headers || {}).filter(([key]) => !["authorization", "cookie", "set-cookie"].includes(key.toLowerCase())));
const event = async (attempt, type, details) => { if (!attempt.issue) return; await writeIssueEvent({ issueId: attempt.issue, eventType: type, actorType: attempt.actorType, actorUser: attempt.actorUser, entityType: "executionAttempt", entityId: attempt._id, stage: attempt.issueStage, phase: attempt.consensusPhase, occurredAt: type === ISSUE_EVENT_TYPES.MODEL_EXECUTION_STARTED ? attempt.startedAt : attempt.completedAt || new Date(), correlationId: attempt.correlationId, details }); };
export const startExecutionAttempt = async (input) => { const attempt = await IssueExecutionAttempt.create({ ...input, status: "running", startedAt: new Date(), application: { status: "pending", appliedAt: null, entityType: null, entityId: null, resultSnapshot: null, error: null } }); await event(attempt, ISSUE_EVENT_TYPES.MODEL_EXECUTION_STARTED, { executionAttemptId: String(attempt._id), scope: attempt.scope, evaluationStage: attempt.evaluationStage, apiModelKey: attempt.modelContext?.apiModelKey ?? null }); return attempt; };
export const executeTrackedDecisionModelRequest = async ({ attemptInput, apiEndpointPath, requestPayload, errorMessage, decisionModelsServiceBaseUrl = process.env.DECISION_MODELS_SERVICE_BASE_URL || "http://localhost:7000", httpClient = axios, normalize }) => {
  const base = decisionModelsServiceBaseUrl.replace(/\/+$/g, ""); const url = `${base}${apiEndpointPath}`;
  const attempt = await startExecutionAttempt({ ...attemptInput, request: { body: clone(requestPayload, {}), method: "POST", apiEndpointPath, resolvedUrl: url, serviceBaseUrl: base } }); const clock = performance.now(); let response;
  try { response = await httpClient.post(url, requestPayload); } catch (error) { const now = new Date(); await IssueExecutionAttempt.updateOne({ _id: attempt._id, status: "running" }, { $set: { status: "failed", failureStage: "transport", completedAt: now, durationMs: Math.max(0, performance.now()-clock), transportDurationMs: Math.max(0, performance.now()-clock), response: error?.response ? { httpStatus: error.response.status ?? null, headers: safeHeaders(error.response.headers), rawBody: clone(error.response.data), unwrappedBody: null } : null, error: serializeExecutionError(error), application: { status: "notApplicable", appliedAt: null, entityType: null, entityId: null, resultSnapshot: null, error: null } } }); const failed = await IssueExecutionAttempt.findById(attempt._id); await event(failed, ISSUE_EVENT_TYPES.MODEL_EXECUTION_FAILED, { executionAttemptId: String(attempt._id), scope: attempt.scope, failureStage: "transport", durationMs: failed.durationMs }); throw createModelApiRequestError(error, errorMessage); }
  const receivedAt = new Date(); const transportDurationMs = Math.max(0, performance.now()-clock); const transport = { httpStatus: response?.status ?? null, headers: safeHeaders(response?.headers), rawBody: clone(response?.data), unwrappedBody: null };
  let unwrapped; try { unwrapped = unwrapModelApiResponse(response, errorMessage); transport.unwrappedBody = clone(unwrapped); } catch (error) { await IssueExecutionAttempt.updateOne({ _id: attempt._id, status: "running" }, { $set: { status:"failed", failureStage:"responseEnvelope", responseReceivedAt:receivedAt, completedAt:new Date(), durationMs:Math.max(0,performance.now()-clock), transportDurationMs, response:transport, error:serializeExecutionError(error), application:{status:"notApplicable",appliedAt:null,entityType:null,entityId:null,resultSnapshot:null,error:null} } }); const failed=await IssueExecutionAttempt.findById(attempt._id); await event(failed, ISSUE_EVENT_TYPES.MODEL_EXECUTION_FAILED,{executionAttemptId:String(attempt._id),scope:attempt.scope,failureStage:"responseEnvelope",durationMs:failed.durationMs}); throw error; }
  try { const normalizedResult = await normalize(unwrapped); const completedAt=new Date(); await IssueExecutionAttempt.updateOne({ _id:attempt._id,status:"running" },{$set:{status:"succeeded",responseReceivedAt:receivedAt,completedAt,durationMs:Math.max(0,performance.now()-clock),transportDurationMs,response:transport,normalizedResult:clone(normalizedResult)}}); const succeeded=await IssueExecutionAttempt.findById(attempt._id); await event(succeeded, ISSUE_EVENT_TYPES.MODEL_EXECUTION_SUCCEEDED,{executionAttemptId:String(attempt._id),scope:attempt.scope,evaluationStage:attempt.evaluationStage,durationMs:succeeded.durationMs}); return { result: normalizedResult, attempt: succeeded }; } catch(error) { await IssueExecutionAttempt.updateOne({_id:attempt._id,status:"running"},{$set:{status:"failed",failureStage:"normalization",responseReceivedAt:receivedAt,completedAt:new Date(),durationMs:Math.max(0,performance.now()-clock),transportDurationMs,response:transport,error:serializeExecutionError(error),application:{status:"notApplicable",appliedAt:null,entityType:null,entityId:null,resultSnapshot:null,error:null}}}); const failed=await IssueExecutionAttempt.findById(attempt._id); await event(failed,ISSUE_EVENT_TYPES.MODEL_EXECUTION_FAILED,{executionAttemptId:String(attempt._id),scope:attempt.scope,failureStage:"normalization",durationMs:failed.durationMs}); throw error; }
};
export const markExecutionApplied = async ({ attemptId, entityType, entityId, resultSnapshot }) => { const appliedAt=new Date(); const attempt=await IssueExecutionAttempt.findOneAndUpdate({_id:attemptId,"application.status":"pending"},{$set:{application:{status:"applied",appliedAt,entityType,entityId,resultSnapshot:clone(resultSnapshot),error:null}}},{new:true}); if (attempt) await event(attempt,ISSUE_EVENT_TYPES.MODEL_EXECUTION_APPLIED,{executionAttemptId:String(attempt._id),scope:attempt.scope}); return attempt; };
export const markExecutionApplicationFailed = async ({ attemptId, error }) => { const attempt=await IssueExecutionAttempt.findOneAndUpdate({_id:attemptId,"application.status":"pending"},{$set:{application:{status:"failed",appliedAt:null,entityType:null,entityId:null,resultSnapshot:null,error:serializeExecutionError(error)}}},{new:true}); if (attempt) await event(attempt,ISSUE_EVENT_TYPES.MODEL_EXECUTION_APPLICATION_FAILED,{executionAttemptId:String(attempt._id),scope:attempt.scope}); return attempt; };
