import { performance } from "node:perf_hooks";
import axios from "axios";
import { IssueExecutionAttempt } from "../../../models/IssueExecutionAttempts.js";
import { createModelApiRequestError, unwrapModelApiResponse } from "../../../services/modelApi/modelResponse.js";
import { writeIssueEvent, ISSUE_EVENT_TYPES } from "../events/index.js";

export const cloneRequiredExecutionEvidence = (value, field) => { if (value === undefined) throw new TypeError(`${field} is required`); try { return JSON.parse(JSON.stringify(value)); } catch { throw new TypeError(`${field} must be JSON-compatible`); } };
const cloneOptional = (value) => { try { return value === undefined ? null : JSON.parse(JSON.stringify(value)); } catch { return null; } };
export const serializeExecutionError = (error) => ({ name: error?.name || "Error", message: error?.message || String(error), code: error?.code ?? null, status: error?.status ?? error?.statusCode ?? error?.response?.status ?? null, field: error?.field ?? null, details: cloneOptional(error?.details), responseBody: cloneOptional(error?.response?.data) });
const safeHeaders = (headers) => Object.fromEntries(Object.entries(headers || {}).filter(([k]) => !["authorization", "cookie", "set-cookie"].includes(k.toLowerCase())));
const pending = () => ({ status: "pending", completedAt: null, entityType: null, entityId: null, resultSnapshot: null, error: null });
const notApplicable = () => ({ status: "notApplicable", completedAt: null, entityType: null, entityId: null, resultSnapshot: null, error: null });
const event = async (attempt, eventType, details, occurredAt) => { if (!attempt.issue) return; await writeIssueEvent({ issueId: attempt.issue, eventType, actorType: attempt.actorType, actorUser: attempt.actorUser, entityType: "executionAttempt", entityId: attempt._id, stage: attempt.issueStage, phase: attempt.consensusPhase, occurredAt, correlationId: attempt.correlationId, details }); };
const terminal = async (attemptId, fields, eventType, details) => { const attempt = await IssueExecutionAttempt.findOneAndUpdate({ _id: attemptId, status: "running" }, { $set: fields }, { new: true }); if (attempt) await event(attempt, eventType, details, attempt.completedAt); return attempt; };
export const startExecutionAttempt = async (input) => { const attempt = await IssueExecutionAttempt.create({ ...input, request: cloneRequiredExecutionEvidence(input.request, "request"), modelContext: cloneRequiredExecutionEvidence(input.modelContext, "modelContext"), status: "running", startedAt: new Date(), application: pending() }); await event(attempt, ISSUE_EVENT_TYPES.MODEL_EXECUTION_STARTED, { executionAttemptId: String(attempt._id), scope: attempt.scope, evaluationStage: attempt.evaluationStage, apiModelKey: attempt.modelContext?.apiModelKey ?? null }, attempt.startedAt); return attempt; };
export const executeTrackedDecisionModelRequest = async ({ attemptInput, apiEndpointPath, requestPayload, errorMessage, decisionModelsServiceBaseUrl = process.env.DECISION_MODELS_SERVICE_BASE_URL || "http://localhost:7000", httpClient = axios, normalize }) => {
  const base = decisionModelsServiceBaseUrl.replace(/\/+$/g, ""); const url = `${base}${apiEndpointPath}`; const request = { body: cloneRequiredExecutionEvidence(requestPayload, "request.body"), method: "POST", apiEndpointPath, resolvedUrl: url, serviceBaseUrl: base }; const attempt = await startExecutionAttempt({ ...attemptInput, request }); const began = performance.now(); let response;
  try { response = await httpClient.post(url, requestPayload); } catch (error) { const completedAt = new Date(), durationMs = Math.max(0, performance.now() - began); await terminal(attempt._id, { status: "failed", failureStage: "transport", completedAt, durationMs, transportDurationMs: durationMs, response: error?.response ? { httpStatus: error.response.status ?? null, headers: safeHeaders(error.response.headers), rawBody: cloneOptional(error.response.data), unwrappedBody: null } : null, error: serializeExecutionError(error), application: notApplicable() }, ISSUE_EVENT_TYPES.MODEL_EXECUTION_FAILED, { executionAttemptId: String(attempt._id), scope: attempt.scope, failureStage: "transport", durationMs }); throw createModelApiRequestError(error, errorMessage); }
  const responseReceivedAt = new Date(), transportDurationMs = Math.max(0, performance.now() - began), responseEvidence = { httpStatus: response?.status ?? null, headers: safeHeaders(response?.headers), rawBody: cloneOptional(response?.data), unwrappedBody: null }; let unwrapped;
  try { unwrapped = unwrapModelApiResponse(response, errorMessage); responseEvidence.unwrappedBody = cloneRequiredExecutionEvidence(unwrapped, "response.unwrappedBody"); } catch (error) { const completedAt = new Date(), durationMs = Math.max(0, performance.now() - began); await terminal(attempt._id, { status: "failed", failureStage: "responseEnvelope", responseReceivedAt, completedAt, durationMs, transportDurationMs, response: responseEvidence, error: serializeExecutionError(error), application: notApplicable() }, ISSUE_EVENT_TYPES.MODEL_EXECUTION_FAILED, { executionAttemptId: String(attempt._id), scope: attempt.scope, failureStage: "responseEnvelope", durationMs }); throw error; }
  try { const normalizedResult = cloneRequiredExecutionEvidence(await normalize(unwrapped), "normalizedResult"), completedAt = new Date(), durationMs = Math.max(0, performance.now() - began); const succeeded = await terminal(attempt._id, { status: "succeeded", responseReceivedAt, completedAt, durationMs, transportDurationMs, response: responseEvidence, normalizedResult }, ISSUE_EVENT_TYPES.MODEL_EXECUTION_SUCCEEDED, { executionAttemptId: String(attempt._id), scope: attempt.scope, evaluationStage: attempt.evaluationStage, durationMs }); return { result: normalizedResult, attempt: succeeded }; } catch (error) { const completedAt = new Date(), durationMs = Math.max(0, performance.now() - began); await terminal(attempt._id, { status: "failed", failureStage: "normalization", responseReceivedAt, completedAt, durationMs, transportDurationMs, response: responseEvidence, error: serializeExecutionError(error), application: notApplicable() }, ISSUE_EVENT_TYPES.MODEL_EXECUTION_FAILED, { executionAttemptId: String(attempt._id), scope: attempt.scope, failureStage: "normalization", durationMs }); throw error; }
};
const completeApplication = async ({ attemptId, status, entityType = null, entityId = null, resultSnapshot = null, error = null }) => { const completedAt = new Date(); const application = { status, completedAt, entityType, entityId, resultSnapshot: status === "applied" ? cloneRequiredExecutionEvidence(resultSnapshot, "application.resultSnapshot") : null, error: status === "failed" ? serializeExecutionError(error) : null }; const attempt = await IssueExecutionAttempt.findOneAndUpdate({ _id: attemptId, status: "succeeded", "application.status": "pending" }, { $set: { application } }, { new: true }); if (attempt) await event(attempt, status === "applied" ? ISSUE_EVENT_TYPES.MODEL_EXECUTION_APPLIED : ISSUE_EVENT_TYPES.MODEL_EXECUTION_APPLICATION_FAILED, { executionAttemptId: String(attempt._id), scope: attempt.scope }, completedAt); return attempt; };
export const markExecutionApplied = (input) => completeApplication({ ...input, status: "applied" });
export const markExecutionApplicationFailed = ({ attemptId, error }) => completeApplication({ attemptId, status: "failed", error });
