// Generated by ModelForge.
// Registers the frontend expression-domain type plugin.
//
// constraintExample scaffold seed:
// {
//   "labelCount": null,
//   "alphaRange": {
//     "min": null,
//     "max": null
//   }
// }

import LinguisticTwoTupleScaleCreationForm from "./LinguisticTwoTupleScaleCreationForm";
import LinguisticTwoTupleScaleEvaluationInput from "./LinguisticTwoTupleScaleEvaluationInput";

export const linguisticTwoTupleScaleExpressionDomainType = Object.freeze({
  key: "linguisticTwoTupleScale",
  label: "Linguistic 2-tuple scale",
  description: "Generated scaffold for a linguistic 2-tuple-inspired expression domain type.",
  family: "linguistic",
  constraintExample: {
    labelCount: null,
    alphaRange: {
      min: null,
      max: null,
    },
  },
  CreationForm: LinguisticTwoTupleScaleCreationForm,
  EvaluationInput: LinguisticTwoTupleScaleEvaluationInput,
});
