// Generated by ModelForge.
// TODO: Replace this placeholder with the domain-specific evaluation input.
// This component must emit values accepted by backend validateEvaluation.
//
// When implemented, call onChange(nextValue) with the normalized evaluation value.
//
// evaluationExample scaffold seed:
// {
//   "labelKey": "high"
// }

import { Alert, Stack } from "@mui/material";

export const LinguisticTwoTupleScaleEvaluationInput = ({
  value,
  onChange,
  disabled = false,
  error = false,
  helperText = "",
}) => {
  void value;
  void onChange;
  void disabled;

  return (
    <Stack spacing={1}>
      <Alert severity={error ? "error" : "info"} variant="outlined">
        {helperText || "Generated scaffold. Implement the domain-specific evaluation input here."}
      </Alert>
    </Stack>
  );
};

export default LinguisticTwoTupleScaleEvaluationInput;
