// Generated by ModelForge.
// TODO: Replace this placeholder with the domain-specific evaluation input.
// This component must emit values accepted by backend validateEvaluation.
//
// When implemented, call onChange(nextValue) with the normalized evaluation value.
//
// evaluationExample scaffold seed:
// {
//   "labelKey": "high"
// }

import { MenuItem, TextField } from "@mui/material";

import { normalizeLabelKeyValue } from "../../helpers";

export const LinguisticTwoTupleScaleEvaluationInput = ({
  expressionDomain,
  value,
  onChange,
  disabled = false,
  error = false,
  helperText = "",
}) => {
  const labels = Array.isArray(expressionDomain?.definition?.labels)
    ? expressionDomain.definition.labels
    : [];
  const labelKey = normalizeLabelKeyValue(value);

  return (
    <TextField
      select
      label="Label"
      color="info"
      value={labelKey}
      onChange={(event) => onChange?.({ labelKey: event.target.value })}
      disabled={disabled || labels.length === 0}
      error={Boolean(error)}
      helperText={
        helperText ||
        (labels.length === 0
          ? "This domain has no labels configured."
          : "Select the linguistic label for this evaluation.")
      }
      fullWidth
    >
      {labels.map((labelItem) => (
        <MenuItem key={labelItem.key} value={labelItem.key}>
          {labelItem.label}
        </MenuItem>
      ))}
    </TextField>
  );
};

export default LinguisticTwoTupleScaleEvaluationInput;
