// Generated by ModelForge.
// TODO: Replace this placeholder with domain-specific creation fields.
// This form must emit:
// {
//   name,
//   typeKey: "linguisticTwoTupleScale",
//   definition
// }
//
// Implement the domain-specific definition fields here.
// The backend validateCreation function must accept the definition emitted by this form.
//
// definitionExample scaffold seed:
// {
//   "labelCount": 3,
//   "alphaRange": {
//     "min": -0.5,
//     "max": 0.5
//   },
//   "labels": [
//     {
//       "key": "light",
//       "label": "Light",
//       "index": 0
//     },
//     {
//       "key": "medium",
//       "label": "Medium",
//       "index": 1
//     },
//     {
//       "key": "high",
//       "label": "High",
//       "index": 2
//     }
//   ]
// }

import { Alert, Stack, TextField } from "@mui/material";

import { normalizeDraftName } from "../../helpers";

const DEFAULT_DEFINITION = {
  labelCount: 3,
  alphaRange: {
    min: -0.5,
    max: 0.5,
  },
  labels: [
    {
      key: "light",
      label: "Light",
      index: 0,
    },
    {
      key: "medium",
      label: "Medium",
      index: 1,
    },
    {
      key: "high",
      label: "High",
      index: 2,
    },
  ],
};

const buildDraft = (value, name) => ({
  ...value,
  name: normalizeDraftName(name),
  typeKey: "linguisticTwoTupleScale",
  definition: value?.definition ?? DEFAULT_DEFINITION,
});

export const LinguisticTwoTupleScaleCreationForm = ({
  value,
  onChange,
  disabled = false,
}) => {
  const handleNameChange = (event) => {
    onChange?.(buildDraft(value, event.target.value));
  };

  return (
    <Stack spacing={2}>
      <TextField
        label="Name"
        color="info"
        value={normalizeDraftName(value?.name)}
        onChange={handleNameChange}
        disabled={disabled}
        fullWidth
      />

      <Alert severity="info" variant="outlined">
        Generated scaffold. Implement domain-specific definition fields here.
      </Alert>
    </Stack>
  );
};

export default LinguisticTwoTupleScaleCreationForm;
