# Generated by ModelForge.
# Defines the model registry metadata used by DecisionModelsService.
# Set implementation_status to "ready" only after executor.py and run.py are implemented and tested.

from registry.model_definition import ModelDefinition
from schemas.model_requests import GenericModelExecutionRequest
from .executor import execute_sample_scaffold_model
from .examples import (
    SAMPLE_SCAFFOLD_MODEL_REQUEST_EXAMPLES,
    SAMPLE_SCAFFOLD_MODEL_RESPONSE_EXAMPLES,
)


MODEL_DEFINITION = ModelDefinition(
    api_model_key="sample_scaffold_model",
    api_endpoint_path="/sample_scaffold_model",
    request_model=GenericModelExecutionRequest,
    handler=execute_sample_scaffold_model,
    display_name="Sample Scaffold Model",
    small_description="Sample model generated with Model Forge.",
    extended_description="Generated sample scaffold used to validate the Model Forge preview and apply flow.",
    request_examples=SAMPLE_SCAFFOLD_MODEL_REQUEST_EXAMPLES,
    response_examples=SAMPLE_SCAFFOLD_MODEL_RESPONSE_EXAMPLES,
    more_info_url=None,
    implementation_status="scaffold",
    model_kind="issue",
    evaluation_structure_key="sampleEvaluationStructure",
    supports_consensus=False,
    supports_consensus_simulation=False,
    is_multi_criteria=True,
    uses_criteria_weights=True,
    uses_expert_weights=False,
    uses_fuzzy_criteria_weights=False,
    uses_criterion_types=True,
    supported_domains=['numericContinuous', 'numericDiscrete'],
    parameters=[{'key': 'sample_param',
  'label': 'Sample parameter',
  'parameterStructureKey': 'sampleParameterGlobal',
  'required': True,
  'default': 0.5,
  'restrictions': {'min': 0, 'max': 1}}],
)
