# Generated by ModelForge.
# FastAPI /docs examples for this model endpoint.

from typing import Any


SAMPLE_SCAFFOLD_MODEL_REQUEST_EXAMPLES: dict[str, dict[str, Any]] = {
    "basic_request": {
        "summary": "Basic request",
        "value": {
            "context": {
                "issue": {
                    "id": "665f0b8f6f1e9c12a34b5600",
                    "name": "Supplier selection 2026",
                    "consensusThreshold": 0.75,
                    "consensusMaxPhases": 3,
                },
                "alternatives": [
                    {"id": "665f0b8f6f1e9c12a34b5672", "name": "Supplier A"},
                    {"id": "665f0b8f6f1e9c12a34b5673", "name": "Supplier B"},
                ],
                "criteria": [
                    {"id": "665f0b8f6f1e9c12a34b5674", "name": "Cost", "type": "cost"},
                    {"id": "665f0b8f6f1e9c12a34b5675", "name": "Quality", "type": "benefit"},
                ],
                "consensusPhase": 0,
                "previousStageResult": None,
                "structure": {
                    "key": "sampleEvaluationStructure",
                    "stage": "alternativeEvaluation",
                },
            },
            "modelParameters": {},
            "evaluations": [
                {
                    "expert": {
                        "id": "665f0b8f6f1e9c12a34b5681",
                        "name": "Ana Torres",
                        "email": "ana.torres@example.com",
                    },
                    "payload": {},
                },
                {
                    "expert": {
                        "id": "665f0b8f6f1e9c12a34b5682",
                        "name": "Luis Romero",
                        "email": "luis.romero@example.com",
                    },
                    "payload": {},
                },
            ],
        },
    }
}
# Criteria-weighting model requests use the same shape, but context.alternatives
# is omitted in runtime requests.


SAMPLE_SCAFFOLD_MODEL_RESPONSE_EXAMPLES: dict[str, dict[str, Any]] = {
    "under_development": {
        "summary": "Generated scaffold under development",
        "value": {
            "success": False,
            "message": "Sample Scaffold Model is a generated scaffold and is still under development.",
            "data": None,
            "error": {
                "code": "MODEL_UNDER_DEVELOPMENT",
                "field": None,
                "details": None,
            },
        },
    }
}
