export const ISSUE_NAME_MAX_LENGTH = 80;
export const ALTERNATIVE_NAME_MAX_LENGTH = 60;
export const CRITERION_NAME_MAX_LENGTH = 60;
export const ISSUE_DESCRIPTION_MAX_LENGTH = 500;
export const ALTERNATIVE_DESCRIPTION_MAX_LENGTH = 500;
export const CRITERION_DESCRIPTION_MAX_LENGTH = 500;
