# Generated by ModelForge.
# Declares this model's DecisionModelsService contract.
# See IMPLEMENTATION_GUIDE.md.

from registry.model_definition import ModelDefinition
from schemas.model_requests import GenericModelExecutionRequest
from .executor import execute_preference_order_criteria_weights
from .examples import (
    PREFERENCE_ORDER_CRITERIA_WEIGHTS_REQUEST_EXAMPLES,
    PREFERENCE_ORDER_CRITERIA_WEIGHTS_RESPONSE_EXAMPLES,
)


MODEL_DEFINITION = ModelDefinition(
    api_model_key="preference_order_criteria_weights",
    api_endpoint_path="/preference_order_criteria_weights",
    request_model=GenericModelExecutionRequest,
    handler=execute_preference_order_criteria_weights,
    display_name="Preference Order Criteria Weights",
    small_description="Derives normalized criterion weights from a complete preference order.",
    extended_description="Auxiliary criteria-weighting model that transforms each complete ordinal ranking of the leaf criteria into a normalized utility vector using positional scores. It supports creator-side and expert-side weighting. Expert-derived numeric weight vectors can be aggregated through the existing MCC criteria consensus workflow.",
    request_examples=PREFERENCE_ORDER_CRITERIA_WEIGHTS_REQUEST_EXAMPLES,
    response_examples=PREFERENCE_ORDER_CRITERIA_WEIGHTS_RESPONSE_EXAMPLES,
    more_info_url=None,
    implementation_status="ready",
    model_kind="criteriaWeighting",
    evaluation_structure_key="criteriaPreferenceOrder",
    supports_creator_criteria_weighting=True,
    supports_expert_criteria_weighting=True,
    supports_consensus=False,
    supports_consensus_simulation=False,
    is_multi_criteria=True,
    uses_criteria_weights=False,
    uses_expert_weights=False,
    uses_fuzzy_criteria_weights=False,
    uses_criterion_types=False,
    supported_expression_domains=[],
    parameters=[],
)