# Generated by ModelForge.
# API documentation examples only.
# See IMPLEMENTATION_GUIDE.md.

from typing import Any


PREFERENCE_ORDER_CRITERIA_WEIGHTS_REQUEST_EXAMPLES: dict[
    str,
    dict[str, Any],
] = {
    "complete_preference_order": {
        "summary": "Complete criteria preference-order evaluation",
        "value": {
            "modelParameters": {},
            "evaluations": [
                {
                    "expert": {
                        "id": "EXPERT_1",
                        "name": "Expert A",
                        "email": "expert.a@example.com",
                    },
                    "payload": {
                        "criterionOrder": [
                            "CRIT_2",
                            "CRIT_1",
                            "CRIT_3",
                        ]
                    },
                }
            ],
            "context": {
                "criteria": [
                    {
                        "id": "CRIT_1",
                        "name": "Cost",
                        "type": "cost",
                    },
                    {
                        "id": "CRIT_2",
                        "name": "Quality",
                        "type": "benefit",
                    },
                    {
                        "id": "CRIT_3",
                        "name": "Delivery time",
                        "type": "cost",
                    },
                ],
                "structure": {
                    "key": "criteriaPreferenceOrder",
                    "stage": "criteriaWeighting",
                },
            },
        },
    }
}


PREFERENCE_ORDER_CRITERIA_WEIGHTS_RESPONSE_EXAMPLES: dict[
    str,
    dict[str, Any],
] = {
    "success": {
        "summary": "Successfully computed criteria weights",
        "value": {
            "success": True,
            "message": "Preference Order Criteria Weights executed successfully",
            "data": {
                "message": "Criteria weights computed successfully",
                "consensusMeasure": None,
                "weightsByCriterion": {
                    "CRIT_1": 0.3333333333333333,
                    "CRIT_2": 0.5,
                    "CRIT_3": 0.16666666666666666,
                },
                "collectiveEvaluations": {
                    "weightsByCriterion": {
                        "CRIT_1": 0.3333333333333333,
                        "CRIT_2": 0.5,
                        "CRIT_3": 0.16666666666666666,
                    }
                },
                "rawOutput": {
                    "useMcc": False,
                    "expertWeightsByExpert": {
                        "expert.a@example.com": {
                            "CRIT_1": 0.3333333333333333,
                            "CRIT_2": 0.5,
                            "CRIT_3": 0.16666666666666666,
                        }
                    },
                    "nExperts": 1,
                    "singleExpertKey": "expert.a@example.com",
                },
            },
        },
    }
}
