# Generated by ModelForge.
# API documentation examples only.
# See IMPLEMENTATION_GUIDE.md.

from typing import Any


PREFERENCE_ORDER_CRITERIA_WEIGHTS_REQUEST_EXAMPLES: dict[
    str,
    dict[str, Any],
] = {
    "complete_preference_order": {
        "summary": "Complete criteria preference-order evaluation",
        "value": {
            "modelParameters": {},
            "evaluations": [
                {
                    "expert": {
                        "id": "EXPERT_1",
                        "name": "Expert A",
                        "email": "expert.a@example.com",
                    },
                    "payload": {
                        "criterionOrder": [
                            "CRIT_2",
                            "CRIT_1",
                            "CRIT_3",
                        ]
                    },
                }
            ],
            "context": {
                "criteria": [
                    {
                        "id": "CRIT_1",
                        "name": "Cost",
                        "type": "cost",
                    },
                    {
                        "id": "CRIT_2",
                        "name": "Quality",
                        "type": "benefit",
                    },
                    {
                        "id": "CRIT_3",
                        "name": "Delivery time",
                        "type": "cost",
                    },
                ],
                "structure": {
                    "key": "criteriaPreferenceOrder",
                    "stage": "criteriaWeighting",
                },
            },
        },
    }
}


PREFERENCE_ORDER_CRITERIA_WEIGHTS_RESPONSE_EXAMPLES: dict[
    str,
    dict[str, Any],
] = {
    "under_development": {
        "summary": "Generated scaffold under development",
        "value": {
            "success": False,
            "message": (
                "Preference Order Criteria Weights is a generated scaffold "
                "and is still under development."
            ),
            "data": None,
            "error": {
                "code": "MODEL_UNDER_DEVELOPMENT",
                "field": None,
                "details": None,
            },
        },
    }
}