# Generated by ModelForge.
# API documentation examples only.
# See IMPLEMENTATION_GUIDE.md.

from typing import Any


PREFERENCE_ORDER_CRITERIA_WEIGHTS_REQUEST_EXAMPLES: dict[str, dict[str, Any]] = {
    "scaffold_request": {
        "summary": "Generated scaffold request",
        "value": {
            "modelParameters": {},
            "evaluations": [],
            "context": {
                "structure": {
                    "key": "criteriaPreferenceOrder",
                    "stage": "criteriaWeighting",
                }
            },
        },
    }
}


PREFERENCE_ORDER_CRITERIA_WEIGHTS_RESPONSE_EXAMPLES: dict[str, dict[str, Any]] = {
    "under_development": {
        "summary": "Generated scaffold under development",
        "value": {
            "success": False,
            "message": "Preference Order Criteria Weights is a generated scaffold and is still under development.",
            "data": None,
            "error": {
                "code": "MODEL_UNDER_DEVELOPMENT",
                "field": None,
                "details": None,
            },
        },
    }
}
