# Generated by ModelForge.
# Implements request parsing, orchestration and public response mapping.
# See IMPLEMENTATION_GUIDE.md.

from math import isfinite
from typing import Any

from fastapi.responses import JSONResponse

from schemas.model_requests import GenericModelExecutionRequest
from services.criteria_weights_consensus.mcc_weights import solve_mcc_weights
from services.model_executors.responses import error_response, success_response
from .run import run_preference_order_criteria_weights


UNDER_DEVELOPMENT_MESSAGE = (
    "Preference Order Criteria Weights is a generated scaffold and is still "
    "under development."
)

EXPECTED_STRUCTURE_KEY = "criteriaPreferenceOrder"
EXPECTED_STRUCTURE_STAGE = "criteriaWeighting"
WEIGHT_SUM_TOLERANCE = 1e-6


class ModelInputError(ValueError):
    """Raised when the model execution request is invalid."""


class ModelOutputError(RuntimeError):
    """Raised when a model/MCC result violates the integration contract."""


def _normalize_non_empty_string(value: Any) -> str | None:
    if not isinstance(value, str):
        return None

    normalized = value.strip()

    return normalized if normalized else None


def _normalize_context(context: Any) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    if not isinstance(context, dict):
        raise ModelInputError("context must be an object")

    source_criteria = context.get("criteria")

    if not isinstance(source_criteria, list):
        raise ModelInputError("context.criteria must be a list")

    if not source_criteria:
        raise ModelInputError("context.criteria must contain at least one criterion")

    normalized_criteria: list[dict[str, Any]] = []
    seen_criterion_ids: set[str] = set()

    for index, criterion in enumerate(source_criteria):
        if not isinstance(criterion, dict):
            raise ModelInputError(
                f"context.criteria[{index}] must be an object"
            )

        criterion_id = _normalize_non_empty_string(criterion.get("id"))

        if criterion_id is None:
            raise ModelInputError(
                f"context.criteria[{index}].id must be a non-empty string"
            )

        criterion_name = _normalize_non_empty_string(criterion.get("name"))

        if criterion_name is None:
            raise ModelInputError(
                f"context.criteria[{index}].name must be a non-empty string"
            )

        if criterion_id in seen_criterion_ids:
            raise ModelInputError(
                f"context.criteria contains duplicate criterion id '{criterion_id}'"
            )

        seen_criterion_ids.add(criterion_id)

        normalized_criterion = dict(criterion)
        normalized_criterion["id"] = criterion_id
        normalized_criterion["name"] = criterion_name

        normalized_criteria.append(normalized_criterion)

    normalized_context = dict(context)
    normalized_context["criteria"] = normalized_criteria

    if "structure" in context:
        structure = context["structure"]

        if not isinstance(structure, dict):
            raise ModelInputError("context.structure must be an object")

        structure_key = _normalize_non_empty_string(structure.get("key"))
        structure_stage = _normalize_non_empty_string(structure.get("stage"))

        if structure_key != EXPECTED_STRUCTURE_KEY:
            raise ModelInputError(
                "context.structure.key must be 'criteriaPreferenceOrder'"
            )

        if structure_stage != EXPECTED_STRUCTURE_STAGE:
            raise ModelInputError(
                "context.structure.stage must be 'criteriaWeighting'"
            )

        normalized_structure = dict(structure)
        normalized_structure["key"] = structure_key
        normalized_structure["stage"] = structure_stage

        normalized_context["structure"] = normalized_structure

    return normalized_context, normalized_criteria


def _normalize_model_parameters(model_parameters: Any) -> dict[str, Any]:
    if not isinstance(model_parameters, dict):
        raise ModelInputError("modelParameters must be an object")

    return dict(model_parameters)


def _normalize_criterion_order(
    *,
    payload: Any,
    criterion_ids: list[str],
    evaluation_index: int,
) -> dict[str, list[str]]:
    field = f"evaluations[{evaluation_index}].payload"

    if not isinstance(payload, dict):
        raise ModelInputError(f"{field} must be an object")

    if set(payload.keys()) != {"criterionOrder"}:
        raise ModelInputError(
            f"{field} must contain exactly the criterionOrder property"
        )

    source_order = payload.get("criterionOrder")

    if not isinstance(source_order, list):
        raise ModelInputError(f"{field}.criterionOrder must be a list")

    valid_criterion_ids = set(criterion_ids)
    seen_criterion_ids: set[str] = set()
    normalized_order: list[str] = []

    for criterion_index, source_criterion_id in enumerate(source_order):
        criterion_id = _normalize_non_empty_string(source_criterion_id)

        if criterion_id is None:
            raise ModelInputError(
                f"{field}.criterionOrder[{criterion_index}] "
                "must be a non-empty string"
            )

        if criterion_id not in valid_criterion_ids:
            raise ModelInputError(
                f"{field}.criterionOrder[{criterion_index}] references "
                f"unknown criterion id '{criterion_id}'"
            )

        if criterion_id in seen_criterion_ids:
            raise ModelInputError(
                f"{field}.criterionOrder contains duplicate criterion id "
                f"'{criterion_id}'"
            )

        seen_criterion_ids.add(criterion_id)
        normalized_order.append(criterion_id)

    if len(normalized_order) != len(criterion_ids):
        raise ModelInputError(
            f"{field}.criterionOrder must contain every current criterion "
            "exactly once"
        )

    if seen_criterion_ids != valid_criterion_ids:
        missing_criterion_ids = [
            criterion_id
            for criterion_id in criterion_ids
            if criterion_id not in seen_criterion_ids
        ]

        raise ModelInputError(
            f"{field}.criterionOrder is missing current criteria: "
            f"{', '.join(missing_criterion_ids)}"
        )

    return {
        "criterionOrder": normalized_order,
    }


def _normalize_evaluations(
    *,
    evaluations: Any,
    criterion_ids: list[str],
) -> tuple[list[dict[str, Any]], list[str]]:
    if not isinstance(evaluations, list):
        raise ModelInputError("evaluations must be a list")

    if not evaluations:
        raise ModelInputError(
            "evaluations must contain at least one completed evaluation"
        )

    normalized_evaluations: list[dict[str, Any]] = []
    expert_keys: list[str] = []
    seen_expert_keys: set[str] = set()

    for evaluation_index, evaluation in enumerate(evaluations):
        field = f"evaluations[{evaluation_index}]"

        if not isinstance(evaluation, dict):
            raise ModelInputError(f"{field} must be an object")

        expert = evaluation.get("expert")

        if not isinstance(expert, dict):
            raise ModelInputError(f"{field}.expert must be an object")

        expert_email = _normalize_non_empty_string(expert.get("email"))
        expert_id = _normalize_non_empty_string(expert.get("id"))

        expert_key = expert_email or expert_id

        if expert_key is None:
            raise ModelInputError(
                f"{field}.expert must provide a non-empty email or id"
            )

        if expert_key in seen_expert_keys:
            raise ModelInputError(
                f"evaluations contains duplicate resolved expert key "
                f"'{expert_key}'"
            )

        seen_expert_keys.add(expert_key)
        expert_keys.append(expert_key)

        normalized_expert = dict(expert)

        if expert_email is not None:
            normalized_expert["email"] = expert_email
        else:
            normalized_expert.pop("email", None)

        if expert_id is not None:
            normalized_expert["id"] = expert_id
        else:
            normalized_expert.pop("id", None)

        if isinstance(expert.get("name"), str):
            normalized_expert["name"] = expert["name"].strip()

        normalized_payload = _normalize_criterion_order(
            payload=evaluation.get("payload"),
            criterion_ids=criterion_ids,
            evaluation_index=evaluation_index,
        )

        normalized_evaluations.append(
            {
                "expert": normalized_expert,
                "payload": normalized_payload,
            }
        )

    return normalized_evaluations, expert_keys


def _validate_weight_vector(
    *,
    vector: Any,
    criterion_ids: list[str],
    field: str,
) -> dict[str, float | int]:
    if not isinstance(vector, dict):
        raise ModelOutputError(f"{field} must be an object")

    expected_criterion_ids = set(criterion_ids)

    if set(vector.keys()) != expected_criterion_ids:
        raise ModelOutputError(
            f"{field} must contain exactly every current criterion id"
        )

    validated_vector: dict[str, float | int] = {}
    total = 0.0

    for criterion_id in criterion_ids:
        weight = vector[criterion_id]

        if isinstance(weight, bool) or not isinstance(weight, (int, float)):
            raise ModelOutputError(
                f"{field}.{criterion_id} must be numeric"
            )

        numeric_weight = float(weight)

        if not isfinite(numeric_weight):
            raise ModelOutputError(
                f"{field}.{criterion_id} must be finite"
            )

        if numeric_weight < 0.0 or numeric_weight > 1.0:
            raise ModelOutputError(
                f"{field}.{criterion_id} must be between 0 and 1"
            )

        total += numeric_weight
        validated_vector[criterion_id] = weight

    if abs(total - 1.0) > WEIGHT_SUM_TOLERANCE:
        raise ModelOutputError(
            f"{field} must be a normalized criterion-weight vector"
        )

    return validated_vector


def _validate_run_result(
    *,
    results: Any,
    expert_keys: list[str],
    criterion_ids: list[str],
) -> tuple[dict[str, dict[str, float | int]], int]:
    if not isinstance(results, dict):
        raise ModelOutputError("Model run result must be an object")

    if results.get("success") is not True:
        raise ModelOutputError(
            "A successful model run result was expected"
        )

    data = results.get("data")

    if not isinstance(data, dict):
        raise ModelOutputError("Successful model run data must be an object")

    source_expert_weights = data.get("expertWeightsByExpert")

    if not isinstance(source_expert_weights, dict) or not source_expert_weights:
        raise ModelOutputError(
            "data.expertWeightsByExpert must be a non-empty object"
        )

    expected_expert_keys = set(expert_keys)

    if set(source_expert_weights.keys()) != expected_expert_keys:
        raise ModelOutputError(
            "data.expertWeightsByExpert must contain exactly one vector "
            "per resolved expert"
        )

    n_experts = data.get("nExperts")

    if (
        isinstance(n_experts, bool)
        or not isinstance(n_experts, int)
        or n_experts != len(expert_keys)
    ):
        raise ModelOutputError(
            "data.nExperts must equal the number of evaluated experts"
        )

    expert_weights_by_expert: dict[
        str,
        dict[str, float | int],
    ] = {}

    for expert_key in expert_keys:
        expert_weights_by_expert[expert_key] = _validate_weight_vector(
            vector=source_expert_weights[expert_key],
            criterion_ids=criterion_ids,
            field=f"data.expertWeightsByExpert.{expert_key}",
        )

    return expert_weights_by_expert, n_experts


def _resolve_collective_weights(
    *,
    criteria: list[dict[str, Any]],
    criterion_ids: list[str],
    expert_keys: list[str],
    expert_weights_by_expert: dict[str, dict[str, float | int]],
) -> tuple[dict[str, float | int], dict[str, Any]]:
    if len(expert_keys) == 1:
        single_expert_key = expert_keys[0]

        weights_by_criterion = dict(
            expert_weights_by_expert[single_expert_key]
        )

        raw_output = {
            "useMcc": False,
            "expertWeightsByExpert": {
                expert_key: dict(weights)
                for expert_key, weights in expert_weights_by_expert.items()
            },
            "nExperts": 1,
            "singleExpertKey": single_expert_key,
        }

        return weights_by_criterion, raw_output

    try:
        mcc_result = solve_mcc_weights(
            criteria=criteria,
            expert_weights_by_expert=expert_weights_by_expert,
        )
    except Exception as error:
        raise ModelOutputError(
            f"MCC criteria-weight aggregation failed: {error}"
        ) from error

    if not isinstance(mcc_result, dict):
        raise ModelOutputError("MCC result must be an object")

    weights_by_criterion = _validate_weight_vector(
        vector=mcc_result.get("weightsByCriterion"),
        criterion_ids=criterion_ids,
        field="mcc.weightsByCriterion",
    )

    raw_output = {
        "useMcc": True,
        "expertWeightsByExpert": {
            expert_key: dict(weights)
            for expert_key, weights in expert_weights_by_expert.items()
        },
        "nExperts": len(expert_keys),
        "mcc": mcc_result,
    }

    return weights_by_criterion, raw_output


def execute_preference_order_criteria_weights(
    request: GenericModelExecutionRequest,
) -> dict[str, Any] | JSONResponse:
    try:
        normalized_context, criteria = _normalize_context(request.context)

        criterion_ids = [
            criterion["id"]
            for criterion in criteria
        ]

        normalized_model_parameters = _normalize_model_parameters(
            request.modelParameters
        )

        normalized_evaluations, expert_keys = _normalize_evaluations(
            evaluations=request.evaluations,
            criterion_ids=criterion_ids,
        )

        try:
            results = run_preference_order_criteria_weights(
                context=normalized_context,
                evaluations=normalized_evaluations,
                model_parameters=normalized_model_parameters,
            )
        except NotImplementedError:
            return error_response(
                UNDER_DEVELOPMENT_MESSAGE,
                code="MODEL_UNDER_DEVELOPMENT",
            )

        if not isinstance(results, dict):
            raise ModelOutputError("Model run result must be an object")

        if results.get("success") is not True:
            message = results.get("message")

            if not isinstance(message, str) or not message.strip():
                message = "Error executing Preference Order Criteria Weights"

            return error_response(
                message,
                details=results,
            )

        expert_weights_by_expert, n_experts = _validate_run_result(
            results=results,
            expert_keys=expert_keys,
            criterion_ids=criterion_ids,
        )

        weights_by_criterion, raw_output = _resolve_collective_weights(
            criteria=criteria,
            criterion_ids=criterion_ids,
            expert_keys=expert_keys,
            expert_weights_by_expert=expert_weights_by_expert,
        )

        raw_output["nExperts"] = n_experts

        response_data = {
            "message": "Criteria weights computed successfully",
            "consensusMeasure": None,
            "weightsByCriterion": dict(weights_by_criterion),
            "collectiveEvaluations": {
                "weightsByCriterion": dict(weights_by_criterion),
            },
            "rawOutput": raw_output,
        }

        return success_response(
            "Preference Order Criteria Weights executed successfully",
            response_data,
        )

    except ModelInputError as error:
        return error_response(str(error))

    except Exception as error:
        return error_response(
            f"Error executing Preference Order Criteria Weights: {error}",
            code="INTERNAL_ERROR",
        )
