# Generated by ModelForge.
# Implements request parsing, orchestration and public response mapping.
# See IMPLEMENTATION_GUIDE.md.

from fastapi.responses import JSONResponse

from schemas.model_requests import GenericModelExecutionRequest
from services.model_executors.responses import error_response


def execute_preference_order_criteria_weights(
    request: GenericModelExecutionRequest,
) -> dict | JSONResponse:
    del request

    return error_response(
        "Preference Order Criteria Weights is a generated scaffold and is still under development.",
        code="MODEL_UNDER_DEVELOPMENT",
    )
