# Generated by ModelForge.
# Pure model algorithm boundary.
#
# This model transforms a strict ordinal ranking of criteria into a normalized
# numeric utility vector.
#
# For an expert k and criterion i:
#
#   n     = number of criteria
#   o_i^k = ordinal position of criterion i
#           (1 = most important, n = least important)
#
# First, assign a positional score:
#
#   s_i^k = n - o_i^k + 1
#
# Therefore:
#
#   position 1 -> score n
#   position 2 -> score n - 1
#   ...
#   position n -> score 1
#
# The positional scores are then normalized so that the resulting utility
# vector sums to one:
#
#               s_i^k
#   u_i^k = ----------------
#            sum_j s_j^k
#
# Since:
#
#   sum_{j=1..n} j = n(n + 1) / 2
#
# the normalized utility can also be written as:
#
#             2(n - o_i^k + 1)
#   u_i^k = ---------------------
#                  n(n + 1)
#
# The resulting vector preserves the original strict preference order:
#
#   o_i^k < o_j^k  <=>  u_i^k > u_j^k
#
# This module computes one normalized criterion-weight vector per expert.
# Aggregation across multiple experts is intentionally outside this pure
# algorithm boundary and is handled by executor.py through the existing MCC
# criteria-weight aggregation service.

from typing import Any


def _normalize_non_empty_string(value: Any) -> str | None:
    if not isinstance(value, str):
        return None

    normalized = value.strip()

    return normalized if normalized else None


def _extract_expert_key(
    evaluation: dict[str, Any],
    index: int,
) -> str:
    """
    Resolve the stable expert key used by this model.

    Resolution order:

    1. expert.email
    2. expert.id
    """

    expert = evaluation.get("expert")

    if not isinstance(expert, dict):
        raise ValueError(
            f"Evaluation at index {index} must contain an expert object"
        )

    expert_email = _normalize_non_empty_string(expert.get("email"))

    if expert_email is not None:
        return expert_email

    expert_id = _normalize_non_empty_string(expert.get("id"))

    if expert_id is not None:
        return expert_id

    raise ValueError(
        f"Evaluation at index {index} must provide a non-empty expert email or id"
    )


def _resolve_criterion_ids(
    context: dict[str, Any],
) -> list[str]:
    """
    Resolve the canonical criterion universe from context.criteria.

    The order of context.criteria is used only to keep the returned mapping
    deterministic.

    It is not interpreted as a preference order.

    Expert preference comes exclusively from:
        evaluation.payload.criterionOrder
    """

    criteria = context.get("criteria")

    if not isinstance(criteria, list) or len(criteria) == 0:
        raise ValueError(
            "Preference Order Criteria Weights requires non-empty context.criteria"
        )

    criterion_ids: list[str] = []
    seen_criterion_ids: set[str] = set()

    for index, criterion in enumerate(criteria):
        if not isinstance(criterion, dict):
            raise ValueError(
                f"context.criteria[{index}] must be an object"
            )

        criterion_id = _normalize_non_empty_string(
            criterion.get("id")
        )

        if criterion_id is None:
            raise ValueError(
                f"context.criteria[{index}].id must be a non-empty string"
            )

        if criterion_id in seen_criterion_ids:
            raise ValueError(
                f"context.criteria contains duplicate criterion id "
                f"'{criterion_id}'"
            )

        seen_criterion_ids.add(criterion_id)
        criterion_ids.append(criterion_id)

    return criterion_ids


def _resolve_complete_criterion_order(
    *,
    evaluation: dict[str, Any],
    criterion_ids: list[str],
    evaluation_index: int,
) -> list[str]:
    """
    Resolve one complete strict criterion preference order.

    Expected canonical payload:

        {
            "criterionOrder": [
                "<most-important-criterion-id>",
                ...
                "<least-important-criterion-id>",
            ]
        }

    Every current criterion must appear exactly once.
    """

    payload = evaluation.get("payload")

    if not isinstance(payload, dict):
        raise ValueError(
            f"Evaluation at index {evaluation_index} must contain a payload object"
        )

    if set(payload.keys()) != {"criterionOrder"}:
        raise ValueError(
            f"Evaluation at index {evaluation_index} payload must contain "
            "exactly criterionOrder"
        )

    source_order = payload.get("criterionOrder")

    if not isinstance(source_order, list):
        raise ValueError(
            f"Evaluation at index {evaluation_index} criterionOrder must be a list"
        )

    valid_criterion_ids = set(criterion_ids)
    normalized_order: list[str] = []
    seen_criterion_ids: set[str] = set()

    for position, source_criterion_id in enumerate(source_order):
        criterion_id = _normalize_non_empty_string(
            source_criterion_id
        )

        if criterion_id is None:
            raise ValueError(
                f"Evaluation at index {evaluation_index} criterionOrder "
                f"contains an invalid criterion id at position {position + 1}"
            )

        if criterion_id not in valid_criterion_ids:
            raise ValueError(
                f"Evaluation at index {evaluation_index} criterionOrder "
                f"references unknown criterion id '{criterion_id}'"
            )

        if criterion_id in seen_criterion_ids:
            raise ValueError(
                f"Evaluation at index {evaluation_index} criterionOrder "
                f"contains duplicate criterion id '{criterion_id}'"
            )

        seen_criterion_ids.add(criterion_id)
        normalized_order.append(criterion_id)

    if len(normalized_order) != len(criterion_ids):
        raise ValueError(
            f"Evaluation at index {evaluation_index} criterionOrder must "
            "contain every current criterion exactly once"
        )

    if seen_criterion_ids != valid_criterion_ids:
        raise ValueError(
            f"Evaluation at index {evaluation_index} criterionOrder must "
            "contain exactly the current context criteria"
        )

    return normalized_order


def _build_utility_vector(
    *,
    criterion_ids: list[str],
    criterion_order: list[str],
) -> dict[str, float]:
    """
    Transform one strict ordinal criterion ranking into a normalized utility
    vector.

    For criterion i:

        s_i^k = n - o_i^k + 1

    where o_i^k is its one-based ordinal position.

    The normalized weight is:

                    s_i^k
        u_i^k = ----------------
                 sum_j s_j^k

    Since:

        sum_j s_j^k = n(n + 1) / 2

    this is equivalent to:

                  2(n - o_i^k + 1)
        u_i^k = ---------------------
                       n(n + 1)

    Example for n = 7:

        position 1 -> score 7 -> utility 7/28
        position 2 -> score 6 -> utility 6/28
        position 3 -> score 5 -> utility 5/28
        position 4 -> score 4 -> utility 4/28
        position 5 -> score 3 -> utility 3/28
        position 6 -> score 2 -> utility 2/28
        position 7 -> score 1 -> utility 1/28
    """

    n_criteria = len(criterion_ids)

    if n_criteria == 0:
        raise ValueError(
            "Cannot build a preference-order utility vector without criteria"
        )

    # Sum of the positional scores:
    #
    #   n + (n - 1) + ... + 1
    #
    # which is:
    #
    #   n(n + 1) / 2
    score_sum = n_criteria * (n_criteria + 1) / 2.0

    utility_by_criterion: dict[str, float] = {}

    for zero_based_index, criterion_id in enumerate(criterion_order):
        # Mathematical positions are one-based:
        #
        #   o_i^k = 1, 2, ..., n
        ordinal_position = zero_based_index + 1

        # Positional score:
        #
        #   s_i^k = n - o_i^k + 1
        positional_score = (
            n_criteria
            - ordinal_position
            + 1
        )

        # Normalized utility:
        #
        #               s_i^k
        #   u_i^k = ----------------
        #            sum_j s_j^k
        utility = positional_score / score_sum

        utility_by_criterion[criterion_id] = utility

    # Return criterion weights following the canonical context.criteria order.
    #
    # This only makes the mapping deterministic. It does not modify the expert's
    # preference or the computed values.
    return {
        criterion_id: utility_by_criterion[criterion_id]
        for criterion_id in criterion_ids
    }


def run_preference_order_criteria_weights(
    *,
    context: dict,
    evaluations: list,
    model_parameters: dict,
) -> dict:
    """
    Transform each expert's complete ordinal criterion ranking into one
    normalized criterion-weight vector.

    Each expert is processed independently.

    This pure model boundary does not aggregate experts. When multiple expert
    vectors exist, executor.py performs the collective aggregation using the
    existing MCC service.
    """

    # This model currently has no declared model parameters.
    #
    # Keep the argument because it belongs to the generic generated model
    # boundary, but do not assign algorithmic semantics to it.
    del model_parameters

    try:
        if not isinstance(context, dict):
            raise ValueError(
                "Preference Order Criteria Weights requires context to be an object"
            )

        if not isinstance(evaluations, list) or len(evaluations) == 0:
            raise ValueError(
                "Preference Order Criteria Weights requires at least one "
                "completed evaluation"
            )

        criterion_ids = _resolve_criterion_ids(context)

        expert_weights_by_expert: dict[
            str,
            dict[str, float],
        ] = {}

        for evaluation_index, evaluation in enumerate(evaluations):
            if not isinstance(evaluation, dict):
                raise ValueError(
                    f"Evaluation at index {evaluation_index} must be an object"
                )

            expert_key = _extract_expert_key(
                evaluation,
                evaluation_index,
            )

            if expert_key in expert_weights_by_expert:
                raise ValueError(
                    f"Duplicated preference-order evaluation for expert "
                    f"'{expert_key}'"
                )

            criterion_order = _resolve_complete_criterion_order(
                evaluation=evaluation,
                criterion_ids=criterion_ids,
                evaluation_index=evaluation_index,
            )

            expert_weights_by_expert[expert_key] = (
                _build_utility_vector(
                    criterion_ids=criterion_ids,
                    criterion_order=criterion_order,
                )
            )

        return {
            "success": True,
            "data": {
                "expertWeightsByExpert": expert_weights_by_expert,
                "nExperts": len(expert_weights_by_expert),
            },
        }

    except ValueError as error:
        return {
            "success": False,
            "message": str(error),
        }