// Generated by ModelForge.
// Registers this Parameter Structure UI.
// See IMPLEMENTATION_GUIDE.md.

import TwoTupleAggregationParameterField from "./TwoTupleAggregationParameterField";
import TwoTupleAggregationParameterReadOnly from "./TwoTupleAggregationParameterReadOnly";

export const twoTupleAggregationParameterField = Object.freeze({
  key: "twoTupleAggregation",
  implementationStatus: "ready",
  FieldComponent: TwoTupleAggregationParameterField,
  ReadOnlyComponent: TwoTupleAggregationParameterReadOnly,
});
