// Generated by ModelForge.
// Implements the editable field for this Parameter Structure.
// See IMPLEMENTATION_GUIDE.md.

import { MenuItem, Stack, TextField, Typography } from "@mui/material";

const toNumericDraft = (input) => (input === "" ? "" : Number(input));

const isVisible = (definition, options) => {
  const condition = definition.visibleWhen;
  return !condition || options[condition.field] === condition.equals;
};

const optionValue = (option) =>
  option && typeof option === "object" ? option.value : option;

const optionLabel = (option) =>
  option && typeof option === "object" ? option.label : String(option);

const buildOptions = (methodDefinition, sourceOptions = {}) => {
  const normalized = {};
  const subparameters = Array.isArray(methodDefinition?.subparameters)
    ? methodDefinition.subparameters
    : [];

  subparameters.forEach((definition) => {
    if (!isVisible(definition, normalized)) return;
    const nextValue = sourceOptions[definition.key] ?? definition.default;
    if (nextValue !== undefined) normalized[definition.key] = nextValue;
  });

  return normalized;
};

export const TwoTupleAggregationParameterField = ({
  parameter,
  value,
  onChange,
  error,
  disabled,
  parameterContext,
}) => {
  void parameterContext;

  const methods = Array.isArray(parameter?.restrictions?.methods)
    ? parameter.restrictions.methods
    : [];
  const methodDefinition = methods.find((item) => item?.key === value?.method);
  const method = methodDefinition?.key || "";
  const options = value?.options && typeof value.options === "object" ? value.options : {};
  const visibleSubparameters = Array.isArray(methodDefinition?.subparameters)
    ? methodDefinition.subparameters.filter((definition) => isVisible(definition, options))
    : [];
  const label = parameter?.label || "Aggregation";

  const updateMethod = (nextMethod) => {
    const nextMethodDefinition = methods.find((item) => item?.key === nextMethod);
    onChange({
      method: nextMethod,
      options: buildOptions(nextMethodDefinition),
    });
  };

  const updateOption = (definition, nextValue) => {
    if (!methodDefinition) return;
    onChange({
      method,
      options: buildOptions(methodDefinition, {
        ...options,
        [definition.key]: nextValue,
      }),
    });
  };

  return (
    <Stack spacing={0.75}>
      <TextField
        select
        label={label}
        variant="outlined"
        color="secondary"
        size="small"
        value={method}
        onChange={(event) => updateMethod(event.target.value)}
        disabled={disabled}
        error={Boolean(error)}
        inputProps={{ "aria-label": `${label} method` }}
      >
        {methods.map((item) => (
          <MenuItem key={item.key} value={item.key}>
            {item.label || item.key}
          </MenuItem>
        ))}
      </TextField>

      {methodDefinition ? (
        <Stack direction={{ xs: "column", sm: "row" }} spacing={0.75}>
          {visibleSubparameters.map((definition) => {
            if (definition.type === "select") {
              const choices = Array.isArray(definition.options) ? definition.options : [];
              return (
                <TextField
                  key={definition.key}
                  select
                  label={definition.label || definition.key}
                  variant="outlined"
                  color="secondary"
                  size="small"
                  value={options[definition.key] ?? ""}
                  onChange={(event) => updateOption(definition, event.target.value)}
                  disabled={disabled}
                  error={Boolean(error)}
                  sx={{ minWidth: 190 }}
                >
                  {choices.map((choice) => (
                    <MenuItem key={optionValue(choice)} value={optionValue(choice)}>
                      {optionLabel(choice)}
                    </MenuItem>
                  ))}
                </TextField>
              );
            }

            if (definition.type === "number") {
              return (
                <TextField
                  key={definition.key}
                  label={definition.label || definition.key}
                  type="number"
                  variant="outlined"
                  color="secondary"
                  size="small"
                  value={options[definition.key] ?? ""}
                  onChange={(event) =>
                    updateOption(definition, toNumericDraft(event.target.value))
                  }
                  disabled={disabled}
                  error={Boolean(error)}
                  inputProps={{ step: "any" }}
                />
              );
            }

            return null;
          })}
        </Stack>
      ) : null}

      {error ? <Typography variant="caption" color="error">{error}</Typography> : null}
    </Stack>
  );
};

export default TwoTupleAggregationParameterField;
