// Generated by ModelForge.
// Implements the editable field for this Parameter Structure.
// See IMPLEMENTATION_GUIDE.md.

import { MenuItem, Stack, TextField, Typography } from "@mui/material";

const METHODS = [
  { value: "arithmetic_mean", label: "2-Tuple Arithmetic Mean" },
  { value: "weighted_average", label: "2-Tuple Weighted Average" },
  { value: "l2towa", label: "L2TOWA" },
];

const QUANTIFIERS = [
  { value: "most", label: "Most" },
  { value: "at_least_half", label: "At least half" },
  { value: "as_many_as_possible", label: "As many as possible" },
  { value: "custom", label: "Custom" },
];

const isSupportedMethod = (method) => METHODS.some((item) => item.value === method);
const isSupportedQuantifier = (quantifier) =>
  QUANTIFIERS.some((item) => item.value === quantifier);

const toNumericDraft = (input) => (input === "" ? "" : Number(input));

export const TwoTupleAggregationParameterField = ({
  parameter,
  value,
  onChange,
  error,
  disabled,
  parameterContext,
}) => {
  void parameterContext;

  const method = isSupportedMethod(value?.method) ? value.method : "";
  const options = value?.options && typeof value.options === "object" ? value.options : {};
  const quantifier = isSupportedQuantifier(options.quantifier)
    ? options.quantifier
    : "";
  const label = parameter?.label || "Aggregation";

  const updateMethod = (nextMethod) => {
    onChange({
      method: nextMethod,
      options: nextMethod === "l2towa" ? { quantifier: "most" } : {},
    });
  };

  const updateQuantifier = (nextQuantifier) => {
    onChange({
      method: "l2towa",
      options:
        nextQuantifier === "custom"
          ? { quantifier: "custom", a: 0, b: 1 }
          : { quantifier: nextQuantifier },
    });
  };

  const updateCustomValue = (key, nextValue) => {
    onChange({
      method: "l2towa",
      options: {
        quantifier: "custom",
        a: options.a ?? 0,
        b: options.b ?? 1,
        [key]: toNumericDraft(nextValue),
      },
    });
  };

  return (
    <Stack spacing={0.75}>
      <TextField
        select
        label={label}
        variant="outlined"
        color="secondary"
        size="small"
        value={method}
        onChange={(event) => updateMethod(event.target.value)}
        disabled={disabled}
        error={Boolean(error)}
        inputProps={{ "aria-label": `${label} method` }}
      >
        {METHODS.map((item) => (
          <MenuItem key={item.value} value={item.value}>
            {item.label}
          </MenuItem>
        ))}
      </TextField>

      {method === "l2towa" ? (
        <Stack direction={{ xs: "column", sm: "row" }} spacing={0.75}>
          <TextField
            select
            label="Quantifier"
            variant="outlined"
            color="secondary"
            size="small"
            value={quantifier}
            onChange={(event) => updateQuantifier(event.target.value)}
            disabled={disabled}
            error={Boolean(error)}
            sx={{ minWidth: 190 }}
          >
            {QUANTIFIERS.map((item) => (
              <MenuItem key={item.value} value={item.value}>
                {item.label}
              </MenuItem>
            ))}
          </TextField>

          {quantifier === "custom" ? (
            <>
              <TextField
                label="a"
                type="number"
                variant="outlined"
                color="secondary"
                size="small"
                value={options.a ?? ""}
                onChange={(event) => updateCustomValue("a", event.target.value)}
                disabled={disabled}
                error={Boolean(error)}
                inputProps={{ min: 0, max: 1, step: "any" }}
              />
              <TextField
                label="b"
                type="number"
                variant="outlined"
                color="secondary"
                size="small"
                value={options.b ?? ""}
                onChange={(event) => updateCustomValue("b", event.target.value)}
                disabled={disabled}
                error={Boolean(error)}
                inputProps={{ min: 0, max: 1, step: "any" }}
              />
            </>
          ) : null}
        </Stack>
      ) : null}

      {error ? <Typography variant="caption" color="error">{error}</Typography> : null}
    </Stack>
  );
};

export default TwoTupleAggregationParameterField;
