// Generated by ModelForge.
// Implements read-only presentation for this Parameter Structure.
// See IMPLEMENTATION_GUIDE.md.

import { Stack, Typography } from "@mui/material";

const METHOD_LABELS = {
  arithmetic_mean: "2-Tuple Arithmetic Mean",
  weighted_average: "2-Tuple Weighted Average",
  l2towa: "L2TOWA",
};

const QUANTIFIER_LABELS = {
  most: "Most",
  at_least_half: "At least half",
  as_many_as_possible: "As many as possible",
  custom: "Custom",
};

export const TwoTupleAggregationParameterReadOnly = ({
  parameter,
  value,
  parameterContext,
}) => {
  void parameter;
  void parameterContext;

  const method = METHOD_LABELS[value?.method];
  const options = value?.options;

  if (!method) {
    return <Typography variant="body2" sx={{ fontWeight: 800 }}>—</Typography>;
  }

  const quantifier = QUANTIFIER_LABELS[options?.quantifier];
  const optionSummary =
    value.method === "l2towa" && options?.quantifier === "custom"
      ? `Custom (a: ${String(options.a)}, b: ${String(options.b)})`
      : value.method === "l2towa" && quantifier
        ? quantifier
        : null;

  return (
    <Stack spacing={0.1}>
      <Typography variant="body2" sx={{ fontWeight: 800 }}>
        {method}
      </Typography>
      {optionSummary ? (
        <Typography variant="caption" color="text.secondary">
          {optionSummary}
        </Typography>
      ) : null}
    </Stack>
  );
};

export default TwoTupleAggregationParameterReadOnly;
