// Generated by ModelForge.
// Implements read-only presentation for this Parameter Structure.
// See IMPLEMENTATION_GUIDE.md.

import { Stack, Typography } from "@mui/material";

const isVisible = (definition, options) => {
  const condition = definition.visibleWhen;
  return !condition || options[condition.field] === condition.equals;
};

const optionValue = (option) =>
  option && typeof option === "object" ? option.value : option;

const optionLabel = (definition, value) => {
  const option = definition.options?.find((item) => optionValue(item) === value);
  return option && typeof option === "object" ? option.label : String(value);
};

export const TwoTupleAggregationParameterReadOnly = ({
  parameter,
  value,
  parameterContext,
}) => {
  void parameterContext;

  const methods = Array.isArray(parameter?.restrictions?.methods)
    ? parameter.restrictions.methods
    : [];
  const methodDefinition = methods.find((item) => item?.key === value?.method);
  const options = value?.options && typeof value.options === "object" ? value.options : {};

  if (!methodDefinition) {
    return <Typography variant="body2" sx={{ fontWeight: 800 }}>—</Typography>;
  }

  const visibleSubparameters = Array.isArray(methodDefinition.subparameters)
    ? methodDefinition.subparameters.filter((definition) => isVisible(definition, options))
    : [];
  const optionSummary = visibleSubparameters
    .filter((definition) => options[definition.key] !== undefined)
    .map((definition) => {
      const option = options[definition.key];
      const display =
        definition.type === "select"
          ? optionLabel(definition, option)
          : String(option);
      return `${definition.label || definition.key}: ${display}`;
    })
    .join(" · ");

  return (
    <Stack spacing={0.1}>
      <Typography variant="body2" sx={{ fontWeight: 800 }}>
        {methodDefinition.label || methodDefinition.key}
      </Typography>
      {optionSummary ? (
        <Typography variant="caption" color="text.secondary">
          {optionSummary}
        </Typography>
      ) : null}
    </Stack>
  );
};

export default TwoTupleAggregationParameterReadOnly;
