import { useMemo, useState } from "react";
import { Box, Stack, Typography } from "@mui/material";
import { RelationshipHeatmap, RelationshipNetwork } from "./AlternativeRelationshipsEChart.jsx";
import { RANKING_ALTERNATIVE_COLORS } from "../logic/rankingAlternativeColors.js";
import { alternativeRelationshipsForPhase, buildAlternativeRelationshipsHeatmap, buildRelationshipNetworkNodes } from "../logic/alternativeRelationshipsPresentation.js";

const phaseLabel = (phase) => (phase === 0 ? "Initial" : `Round ${phase}`);
const pct = (value) => `${Math.round(value * 100)}%`;

const AlternativeRelationshipsCard = ({ executions = [] }) => {
  const [focusId, setFocusId] = useState(null);
  const entries = executions.map((execution) => ({ execution, relationship: alternativeRelationshipsForPhase(execution, execution.sourcePhase) })).filter(({ relationship }) => relationship?.pairs?.length);
  if (!entries.length) return null;
  return <Box sx={{ border: "1px solid rgba(83,198,214,0.16)", bgcolor: "rgba(8,18,29,0.88)", borderRadius: 3, p: { xs: 1.5, sm: 2 }, minWidth: 0 }}><Box sx={{ mb: 1.25 }}><Typography variant="h6" component="h2">Alternative relationships</Typography><Typography variant="body2" color="text.secondary">Relative separation between alternatives in the selected phase.</Typography></Box><Stack spacing={1.4} divider={<Box sx={{ borderTop: "1px solid rgba(83,198,214,0.14)" }} />}>{entries.map(({ execution, relationship }) => <ExecutionGroup key={execution.key} execution={execution} relationship={relationship} focusId={focusId} onFocus={setFocusId} />)}</Stack></Box>;
};

const ExecutionGroup = ({ execution, relationship, focusId, onFocus }) => {
  const { alternatives, data } = useMemo(() => buildAlternativeRelationshipsHeatmap(relationship), [relationship]);
  const names = alternatives.map((item) => item.name || item.alternativeId);
  const heatmapOption = useMemo(() => ({ animation: false, grid: { left: 68, right: 8, top: 22, bottom: 52 }, xAxis: { type: "category", data: names, axisLabel: { color: "#d7eef2", fontSize: 10, interval: 0, rotate: names.length > 5 ? 35 : 0 } }, yAxis: { type: "category", data: names, axisLabel: { color: "#d7eef2", fontSize: 10 } }, visualMap: { min: 0, max: 1, calculable: false, orient: "horizontal", left: "center", bottom: 4, itemWidth: 90, itemHeight: 8, text: ["Farther", "Closer"], textStyle: { color: "#b7d7dd", fontSize: 10 }, inRange: { color: ["#143442", "#27bfd5"] } }, tooltip: { trigger: "item", formatter: (params) => { const [x, y, value] = params.value; return `${names[x]} ↔ ${names[y]}<br/>Relative separation: ${pct(value)}<br/>Phase: ${phaseLabel(relationship.phase)}<br/>Execution: ${execution.displayLabel}`; } }, series: [{ type: "heatmap", data, progressive: 0, itemStyle: { borderColor: "rgba(4,15,24,0.55)", borderWidth: 2 } }] }), [data, execution.displayLabel, names, relationship.phase]);
  const networkOption = useMemo(() => { const nodes = buildRelationshipNetworkNodes(alternatives); const nodeCount = nodes.length; return { animation: false, tooltip: { formatter: (params) => { if (params.dataType === "edge") return `${params.data.source} ↔ ${params.data.target}<br/>Relative separation: ${pct(params.data.value)}<br/>Phase: ${phaseLabel(relationship.phase)}<br/>Execution: ${execution.displayLabel}`; return params.data.name; } }, series: [{ type: "graph", layout: "circular", circular: { rotateLabel: false }, roam: false, data: nodes.map((node, index) => ({ id: node.alternativeId, name: node.name || node.alternativeId, symbolSize: Math.max(18, 28 - nodeCount), itemStyle: { color: RANKING_ALTERNATIVE_COLORS[index % RANKING_ALTERNATIVE_COLORS.length], borderColor: focusId === node.alternativeId ? "#fff" : "rgba(4,15,24,0.9)", borderWidth: focusId === node.alternativeId ? 1.5 : 0.7, opacity: focusId && focusId !== node.alternativeId ? 0.32 : 1 }, label: { show: true, color: "#d7eef2", fontSize: 10, formatter: node.name || node.alternativeId } })), links: relationship.pairs.map((pair) => ({ source: pair.leftAlternativeId, target: pair.rightAlternativeId, value: pair.relativeSeparation, lineStyle: { opacity: focusId && pair.leftAlternativeId !== focusId && pair.rightAlternativeId !== focusId ? 0.1 : nodeCount > 5 ? 0.35 : 0.65, width: 1 } })), emphasis: { focus: "adjacency", lineStyle: { width: 2 } } }] }; }, [alternatives, execution.displayLabel, focusId, relationship.pairs, relationship.phase]);
  const click = (params) => { if (params?.dataType !== "node") return; const id = params.data?.id; if (id) onFocus(focusId === id ? null : id); };
  return <Box sx={{ minWidth: 0, pt: 0.6 }} data-testid="alternative-relationships-execution"><Typography variant="subtitle1" sx={{ fontWeight: 900, mb: 0.8, color: execution.color }}>{execution.displayLabel}</Typography><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "repeat(2,minmax(0,1fr))" }, gap: 1.2, alignItems: "start" }}><Box><Typography variant="caption" color="text.secondary">Heatmap</Typography><RelationshipHeatmap option={heatmapOption} onClick={click} /></Box><Box><Typography variant="caption" color="text.secondary">Relationship network</Typography><RelationshipNetwork option={networkOption} onClick={click} /></Box></Box></Box>;
};

export default AlternativeRelationshipsCard;
