// Generated by ModelForge.
// Registers the frontend View for this evaluation structure.

import { EVALUATION_STAGES } from "../../evaluationStages";
import SampleEvaluationStructureView from "./SampleEvaluationStructureView";

export const sampleEvaluationStructureStructure = Object.freeze({
  key: "sampleEvaluationStructure",
  stage: EVALUATION_STAGES.ALTERNATIVE_EVALUATION,
  implementationStatus: "scaffold",
  View: SampleEvaluationStructureView,
});
