// Generated by ModelForge.
// Renders and edits the canonical payload returned by backend get().
// setEvaluationPayload updates the editable payload.
// readOnly controls whether the View should allow edits.
// collectivePayload has the same shape as evaluationPayload.

import { forwardRef, useImperativeHandle } from "react";
import { Alert } from "@mui/material";

const SampleEvaluationStructureView = (
  {
    evaluationContext,
    evaluationPayload,
    setEvaluationPayload,
    collectivePayload,
    readOnly,
    loading,
  },
  ref
) => {
  void evaluationContext;
  void setEvaluationPayload;
  void collectivePayload;
  void readOnly;
  void loading;

  const preparePayloadRead = async () => evaluationPayload;
  const flushPendingEdits = async () => evaluationPayload;

  useImperativeHandle(ref, () => ({
    flushPendingEdits,
    preparePayloadRead,
  }));

  return (
    <Alert severity="info">
      sampleEvaluationStructure is under development.
    </Alert>
  );
};

export default forwardRef(SampleEvaluationStructureView);
