// Generated by ModelForge.
// Global expression-domain type plugin.
// TODO: Implement domain-specific creation and evaluation validation before using this type.
//
// validateCreation receives a payload like:
// {
//   name: "...",
//   definition: ...
// }
//
// It must return:
// {
//   name,
//   typeKey: "linguisticTwoTupleScale",
//   family: "linguistic",
//   definition
// }
//
// validateEvaluation receives:
// {
//   value,
//   expressionDomain
// }
//
// It must return the normalized evaluation value accepted by this domain type.
//
// definitionExample scaffold seed:
// {
//   "labelCount": 3,
//   "alphaRange": {
//     "min": -0.5,
//     "max": 0.5
//   },
//   "labels": [
//     {
//       "key": "light",
//       "label": "Light",
//       "index": 0
//     },
//     {
//       "key": "medium",
//       "label": "Medium",
//       "index": 1
//     },
//     {
//       "key": "high",
//       "label": "High",
//       "index": 2
//     }
//   ]
// }
// evaluationExample scaffold seed:
// {
//   "labelKey": "high"
// }

import { createBadRequestError } from "../../../../../utils/common/errors.js";

export const linguisticTwoTupleScale = Object.freeze({
  key: "linguisticTwoTupleScale",
  label: "Linguistic 2-tuple scale",
  description: "Generated scaffold for a linguistic 2-tuple-inspired expression domain type.",
  family: "linguistic",

  validateCreation(payload = {}) {
    void payload;

    throw createBadRequestError(
      "linguisticTwoTupleScale is a generated scaffold. Implement validateCreation before using it.",
      {
        code: "EXPRESSION_DOMAIN_TYPE_UNDER_DEVELOPMENT",
        details: {
          typeKey: "linguisticTwoTupleScale",
        },
      }
    );
  },

  validateEvaluation({ value, expressionDomain } = {}) {
    void value;
    void expressionDomain;

    throw createBadRequestError(
      "linguisticTwoTupleScale is a generated scaffold. Implement validateEvaluation before using it.",
      {
        code: "EXPRESSION_DOMAIN_TYPE_UNDER_DEVELOPMENT",
        details: {
          typeKey: "linguisticTwoTupleScale",
        },
      }
    );
  },
});
