// Generated by ModelForge.
// Registers the backend validator for this parameter structure.

import { validateSampleParameterGlobalParameter } from "./validate.js";

export const sampleParameterGlobalParameterStructure = Object.freeze({
  key: "sampleParameterGlobal",
  implementationStatus: "scaffold",
  validateAndNormalize: validateSampleParameterGlobalParameter,
});
