# Generated by ModelForge.
# Declares this model's DecisionModelsService contract.
# See IMPLEMENTATION_GUIDE.md.

from registry.model_definition import ModelDefinition
from schemas.model_requests import GenericModelExecutionRequest
from .executor import execute_two_tuple
from .aggregation import AGGREGATION_METHODS
from .examples import (
    TWO_TUPLE_REQUEST_EXAMPLES,
    TWO_TUPLE_RESPONSE_EXAMPLES,
)

MODEL_DEFINITION = ModelDefinition(
    api_model_key="two_tuple",
    api_endpoint_path="/two_tuple",
    request_model=GenericModelExecutionRequest,
    handler=execute_two_tuple,
    display_name="2-TUPLE LINGUISTIC MODEL",
    small_description="Linguistic decision model with configurable 2-tuple aggregation methods for experts and criteria.",
    extended_description="Decision model based on the 2-tuple linguistic representation. It aggregates alternative evaluations in two configurable stages: expert aggregation and criteria aggregation. Each stage can use a different aggregation method and method-specific parameters.",
    request_examples=TWO_TUPLE_REQUEST_EXAMPLES,
    response_examples=TWO_TUPLE_RESPONSE_EXAMPLES,
    more_info_url=None,
    implementation_status="ready",
    model_kind="issue",
    requires_homogeneous_expression_domains=True,
    evaluation_structure_key="alternativeCriteriaMatrix",
    supports_creator_criteria_weighting=False,
    supports_expert_criteria_weighting=False,
    supports_consensus=False,
    supports_consensus_simulation=False,
    is_multi_criteria=True,
    uses_criteria_weights=True,
    uses_expert_weights=True,
    uses_fuzzy_criteria_weights=False,
    uses_criterion_types=False,
    supported_expression_domains=[{"typeKey": "linguistic2Tuple", "constraints": {}}],
    parameters=[
        {
            "key": "expertAggregation",
            "label": "Expert aggregation",
            "parameterStructureKey": "twoTupleAggregation",
            "required": True,
            "default": {"method": "arithmetic_mean", "options": {}},
            "restrictions": {"methods": AGGREGATION_METHODS},
        },
        {
            "key": "criteriaAggregation",
            "label": "Criteria aggregation",
            "parameterStructureKey": "twoTupleAggregation",
            "required": True,
            "default": {"method": "weighted_average", "options": {}},
            "restrictions": {"methods": AGGREGATION_METHODS},
        },
    ],
    model_section={
        "whatItDoes": (
            "The 2-Tuple Linguistic Model is designed for decisions in which people evaluate "
            "alternatives using words instead of exact numbers. Assessments such as low, medium "
            "or high can be represented in a way that preserves small differences that normally "
            "appear when several linguistic opinions are combined.\n\n"
            "The model aggregates the evaluations provided by the experts and then combines the "
            "information across the criteria. Different aggregation strategies can be selected "
            "for these stages, allowing the final collective evaluation to reflect how the group "
            "and the criteria should contribute to the decision."
        ),
        "whenToUse": (
            "Use this model when expert knowledge is naturally qualitative and asking for exact "
            "numerical scores would give a false sense of precision. It is particularly appropriate "
            "when several people evaluate the same alternatives using a common linguistic scale and "
            "the decision needs to combine those opinions systematically.\n\n"
            "It may be less appropriate when accurate numerical measurements are already available, "
            "or when the problem specifically requires a distance-to-ideal ranking such as TOPSIS."
        ),
        "advantages": [
            "Allows evaluations to be expressed using understandable linguistic terms.",
            "Preserves more detail when linguistic assessments are aggregated.",
            "Supports the combination of evaluations from multiple experts.",
            "Provides configurable ways of aggregating expert and criterion information.",
        ],
        "limitations": [
            "Participants need to use compatible linguistic scales.",
            "The aggregation configuration can influence the final result.",
            "The mathematical representation is less intuitive for non-technical users than simple numerical scoring.",
            "It can be unnecessary when reliable numerical measurements are already available.",
        ],
    },
)
