# Generated by ModelForge.
# Declares this model's DecisionModelsService contract.
# See IMPLEMENTATION_GUIDE.md.

from registry.model_definition import ModelDefinition
from schemas.model_requests import GenericModelExecutionRequest
from .executor import execute_two_tuple
from .aggregation import AGGREGATION_METHODS
from .examples import (
    TWO_TUPLE_REQUEST_EXAMPLES,
    TWO_TUPLE_RESPONSE_EXAMPLES,
)


MODEL_DEFINITION = ModelDefinition(
    api_model_key="two_tuple",
    api_endpoint_path="/two_tuple",
    request_model=GenericModelExecutionRequest,
    handler=execute_two_tuple,
    display_name="2-Tuple Linguistic Model",
    small_description="Linguistic decision model with configurable 2-tuple aggregation methods for experts and criteria.",
    extended_description="Decision model based on the 2-tuple linguistic representation. It aggregates alternative evaluations in two configurable stages: expert aggregation and criteria aggregation. Each stage can use a different aggregation method and method-specific parameters.",
    request_examples=TWO_TUPLE_REQUEST_EXAMPLES,
    response_examples=TWO_TUPLE_RESPONSE_EXAMPLES,
    more_info_url=None,
    implementation_status="scaffold",
    model_kind="issue",
    evaluation_structure_key="alternativeCriteriaMatrix",
    supports_creator_criteria_weighting=False,
    supports_expert_criteria_weighting=False,
    supports_consensus=False,
    supports_consensus_simulation=False,
    is_multi_criteria=True,
    uses_criteria_weights=True,
    uses_expert_weights=True,
    uses_fuzzy_criteria_weights=False,
    uses_criterion_types=True,
    supported_expression_domains=[{'typeKey': 'linguistic2Tuple', 'constraints': {}}],
    parameters=[
        {
            "key": "expertAggregation",
            "label": "Expert aggregation",
            "parameterStructureKey": "twoTupleAggregation",
            "required": True,
            "default": {"method": "arithmetic_mean", "options": {}},
            "restrictions": {"methods": AGGREGATION_METHODS},
        },
        {
            "key": "criteriaAggregation",
            "label": "Criteria aggregation",
            "parameterStructureKey": "twoTupleAggregation",
            "required": True,
            "default": {"method": "weighted_average", "options": {}},
            "restrictions": {"methods": AGGREGATION_METHODS},
        },
    ],
)
