// Generated by ModelForge.
// Implements this Evaluation Structure View.
// See IMPLEMENTATION_GUIDE.md.

import { Alert } from "@mui/material";

const CriteriaPreferenceOrderView = ({
  decisionContext,
  evaluation,
  setEvaluation,
  collectiveEvaluation,
  readOnly,
}) => {
  void decisionContext;
  void evaluation;
  void setEvaluation;
  void collectiveEvaluation;
  void readOnly;

  return (
    <Alert severity="info">
      criteriaPreferenceOrder is under development.
    </Alert>
  );
};

export default CriteriaPreferenceOrderView;
