// Generated by ModelForge.
// Implements this Evaluation Structure View.
// See IMPLEMENTATION_GUIDE.md.

import {
  Alert,
  Box,
  Button,
  Divider,
  Paper,
  Stack,
  Typography,
} from "@mui/material";

import CriteriaPreferenceOrderList from "./CriteriaPreferenceOrderList";
import { resolveCriteria } from "./operations/resolveCriteria";
import { resolvePreferenceOrder } from "./operations/resolvePreferenceOrder";

const CriteriaPreferenceOrderView = ({
  decisionContext,
  evaluation,
  setEvaluation,
  collectiveEvaluation,
  readOnly,
}) => {
  void collectiveEvaluation;

  let criteria;

  try {
    criteria = resolveCriteria({ decisionContext });
  } catch {
    return (
      <Alert severity="error">
        Criteria preference order context is invalid.
      </Alert>
    );
  }

  const resolvedPreferenceOrder = resolvePreferenceOrder({
    criteria,
    evaluation,
  });

  if (resolvedPreferenceOrder.error) {
    return <Alert severity="error">{resolvedPreferenceOrder.error}</Alert>;
  }

  const {
    criterionOrder,
    rankedCriteria,
    unrankedCriteria,
  } = resolvedPreferenceOrder;

  const permitEdit = readOnly !== true;

  const emitCriterionOrder = (nextCriterionOrder) => {
    if (!permitEdit) {
      return;
    }

    setEvaluation({
      criterionOrder: nextCriterionOrder,
    });
  };

  const handleMove = (index, offset) => {
    if (!permitEdit) {
      return;
    }

    const nextIndex = index + offset;

    if (nextIndex < 0 || nextIndex >= criterionOrder.length) {
      return;
    }

    const nextCriterionOrder = [...criterionOrder];

    [
      nextCriterionOrder[index],
      nextCriterionOrder[nextIndex],
    ] = [
      nextCriterionOrder[nextIndex],
      nextCriterionOrder[index],
    ];

    emitCriterionOrder(nextCriterionOrder);
  };

  const handleRemove = (criterionId) => {
    if (!permitEdit) {
      return;
    }

    emitCriterionOrder(
      criterionOrder.filter((currentCriterionId) => {
        return currentCriterionId !== criterionId;
      })
    );
  };

  const handleAdd = (criterionId) => {
    if (!permitEdit) {
      return;
    }

    emitCriterionOrder([
      ...criterionOrder,
      criterionId,
    ]);
  };

  if (criteria.length === 0) {
    return (
      <Alert severity="info">
        No current leaf criteria are available to rank.
      </Alert>
    );
  }

  return (
    <Box
      sx={{
        width: "100%",
        maxWidth: "none",
        minWidth: 0,
        p: { xs: 1, sm: 1.5 },
      }}
    >
      <Stack spacing={1.5}>
        <Box>
          <Typography variant="subtitle2">
            Criteria preference order
          </Typography>

          <Typography
            variant="caption"
            color="text.secondary"
          >
            Importance decreases from top to bottom.
          </Typography>
        </Box>

        <Box>
          <Stack spacing={0.75}>
            <Box>
              <Typography variant="subtitle2">
                Ranked criteria
              </Typography>

              <Typography
                variant="caption"
                color="text.secondary"
              >
                The first criterion is the most important.
              </Typography>
            </Box>

            {rankedCriteria.length === 0 ? (
              <Alert severity="info">
                No criteria have been ranked yet. Add a criterion below to
                begin establishing the preference order.
              </Alert>
            ) : (
              <CriteriaPreferenceOrderList
                criteria={rankedCriteria}
                readOnly={!permitEdit}
                onChange={(nextCriteria) => {
                  emitCriterionOrder(nextCriteria.map((criterion) => criterion.id));
                }}
                onMove={handleMove}
                onRemove={handleRemove}
              />
            )}
          </Stack>
        </Box>

        {unrankedCriteria.length > 0 ? (
          <>
            <Divider />

            <Box>
            <Stack spacing={0.75}>
              <Box>
                <Typography variant="subtitle2">
                  {permitEdit ? "Available criteria" : "Not ranked"}
                </Typography>

                <Typography
                  variant="caption"
                  color="text.secondary"
                >
                  {permitEdit
                    ? "Adding a criterion places it at the end of the current ranking."
                    : "These criteria are not included in the stored ranking."}
                </Typography>
              </Box>

              {unrankedCriteria.map((criterion) => {
                const criterionName = criterion.name || criterion.id;

                return (
                  <Paper
                    key={criterion.id}
                    variant="outlined"
                    sx={{
                      p: 1,
                      borderRadius: 2,
                      borderColor: "divider",
                      bgcolor: "background.paper",
                    }}
                  >
                    <Stack
                      direction="row"
                      spacing={1}
                      alignItems="center"
                      justifyContent="space-between"
                    >
                      <Typography
                        variant="body2"
                        sx={{
                          minWidth: 0,
                          overflowWrap: "anywhere",
                        }}
                      >
                        {criterionName}
                      </Typography>

                      {permitEdit ? (
                        <Button
                          size="small"
                          variant="outlined"
                          color="info"
                          aria-label={`Add ${criterionName} to ranking`}
                          onClick={() => {
                            handleAdd(criterion.id);
                          }}
                          sx={{
                            flexShrink: 0,
                          }}
                        >
                          Add
                        </Button>
                      ) : null}
                    </Stack>
                  </Paper>
                );
              })}
            </Stack>
            </Box>
          </>
        ) : null}
      </Stack>
    </Box>
  );
};

export default CriteriaPreferenceOrderView;
