// Generated by ModelForge.
// Implements this Evaluation Structure View.
// See IMPLEMENTATION_GUIDE.md.

import {
  Alert,
  Box,
  Button,
  Divider,
  IconButton,
  Paper,
  Stack,
  Tooltip,
  Typography,
} from "@mui/material";

import { resolveCriteria } from "./operations/resolveCriteria";
import { resolvePreferenceOrder } from "./operations/resolvePreferenceOrder";

const CriteriaPreferenceOrderView = ({
  decisionContext,
  evaluation,
  setEvaluation,
  collectiveEvaluation,
  readOnly,
}) => {
  void collectiveEvaluation;

  let criteria;

  try {
    criteria = resolveCriteria({ decisionContext });
  } catch {
    return (
      <Alert severity="error">
        Criteria preference order context is invalid.
      </Alert>
    );
  }

  const resolvedPreferenceOrder = resolvePreferenceOrder({
    criteria,
    evaluation,
  });

  if (resolvedPreferenceOrder.error) {
    return <Alert severity="error">{resolvedPreferenceOrder.error}</Alert>;
  }

  const {
    criterionOrder,
    rankedCriteria,
    unrankedCriteria,
  } = resolvedPreferenceOrder;

  const permitEdit = readOnly !== true;

  const emitCriterionOrder = (nextCriterionOrder) => {
    if (!permitEdit) {
      return;
    }

    setEvaluation({
      criterionOrder: nextCriterionOrder,
    });
  };

  const handleMove = (index, offset) => {
    if (!permitEdit) {
      return;
    }

    const nextIndex = index + offset;

    if (nextIndex < 0 || nextIndex >= criterionOrder.length) {
      return;
    }

    const nextCriterionOrder = [...criterionOrder];

    [
      nextCriterionOrder[index],
      nextCriterionOrder[nextIndex],
    ] = [
      nextCriterionOrder[nextIndex],
      nextCriterionOrder[index],
    ];

    emitCriterionOrder(nextCriterionOrder);
  };

  const handleRemove = (criterionId) => {
    if (!permitEdit) {
      return;
    }

    emitCriterionOrder(
      criterionOrder.filter((currentCriterionId) => {
        return currentCriterionId !== criterionId;
      })
    );
  };

  const handleAdd = (criterionId) => {
    if (!permitEdit) {
      return;
    }

    emitCriterionOrder([
      ...criterionOrder,
      criterionId,
    ]);
  };

  if (criteria.length === 0) {
    return (
      <Alert severity="info">
        No current leaf criteria are available to rank.
      </Alert>
    );
  }

  return (
    <Box
      sx={{
        width: "100%",
        maxWidth: "none",
        minWidth: 0,
        p: { xs: 1, sm: 1.5 },
      }}
    >
      <Stack spacing={1.5}>
        <Box>
          <Typography variant="subtitle2">
            Criteria preference order
          </Typography>

          <Typography
            variant="caption"
            color="text.secondary"
          >
            Importance decreases from top to bottom.
          </Typography>
        </Box>

        <Box>
          <Stack spacing={0.75}>
            <Box>
              <Typography variant="subtitle2">
                Ranked criteria
              </Typography>

              <Typography
                variant="caption"
                color="text.secondary"
              >
                The first criterion is the most important.
              </Typography>
            </Box>

            {rankedCriteria.length === 0 ? (
              <Alert severity="info">
                No criteria have been ranked yet. Add a criterion below to
                begin establishing the preference order.
              </Alert>
            ) : (
              <Stack spacing={0.75}>
                {rankedCriteria.map((criterion, index) => {
                  const displayRank = index + 1;
                  const isFirst = index === 0;
                  const isLast = index === rankedCriteria.length - 1;
                  const criterionName = criterion.name || criterion.id;

                  return (
                    <Paper
                      key={criterion.id}
                      variant="outlined"
                      sx={{
                        p: 1,
                        borderRadius: 2,
                        borderColor: "divider",
                        bgcolor: "background.paper",
                      }}
                    >
                      <Stack
                        direction={{
                          xs: "column",
                          sm: "row",
                        }}
                        spacing={1}
                        alignItems={{
                          xs: "stretch",
                          sm: "center",
                        }}
                      >
                        <Stack
                          direction="row"
                          spacing={1}
                          alignItems="center"
                          sx={{
                            flex: 1,
                            minWidth: 0,
                          }}
                        >
                          <Box
                            sx={{
                              display: "flex",
                              alignItems: "center",
                              justifyContent: "center",
                              width: 30,
                              height: 30,
                              flexShrink: 0,
                              border: 1,
                              borderColor: "info.main",
                              borderRadius: 1.5,
                              color: "info.main",
                            }}
                          >
                            <Typography
                              variant="body2"
                              fontWeight="bold"
                            >
                              {displayRank}
                            </Typography>
                          </Box>

                          <Box
                            sx={{
                              minWidth: 0,
                              flex: 1,
                            }}
                          >
                            <Typography
                              variant="body2"
                              sx={{
                                overflowWrap: "anywhere",
                              }}
                            >
                              {criterionName}
                            </Typography>

                            {isFirst ? (
                              <Typography
                                variant="caption"
                                color="info.main"
                              >
                                Most important
                              </Typography>
                            ) : null}

                            {isLast && rankedCriteria.length > 1 ? (
                              <Typography
                                variant="caption"
                                color="text.secondary"
                              >
                                Least important
                              </Typography>
                            ) : null}
                          </Box>
                        </Stack>

                        {permitEdit ? (
                          <Stack
                            direction="row"
                            spacing={0.25}
                            justifyContent={{
                              xs: "flex-end",
                              sm: "initial",
                            }}
                            flexShrink={0}
                          >
                            <Tooltip
                              title={`Move ${criterionName} up`}
                            >
                              <span>
                                <IconButton
                                  size="small"
                                  disabled={isFirst}
                                  aria-label={`Move ${criterionName} up`}
                                  onClick={() => {
                                    handleMove(index, -1);
                                  }}
                                >
                                  <Box
                                    component="span"
                                    aria-hidden="true"
                                    sx={{
                                      fontSize: "1.1rem",
                                      lineHeight: 1,
                                    }}
                                  >
                                    ↑
                                  </Box>
                                </IconButton>
                              </span>
                            </Tooltip>

                            <Tooltip
                              title={`Move ${criterionName} down`}
                            >
                              <span>
                                <IconButton
                                  size="small"
                                  disabled={isLast}
                                  aria-label={`Move ${criterionName} down`}
                                  onClick={() => {
                                    handleMove(index, 1);
                                  }}
                                >
                                  <Box
                                    component="span"
                                    aria-hidden="true"
                                    sx={{
                                      fontSize: "1.1rem",
                                      lineHeight: 1,
                                    }}
                                  >
                                    ↓
                                  </Box>
                                </IconButton>
                              </span>
                            </Tooltip>

                            <Tooltip
                              title={`Remove ${criterionName} from ranking`}
                            >
                              <IconButton
                                size="small"
                                aria-label={`Remove ${criterionName} from ranking`}
                                onClick={() => {
                                  handleRemove(criterion.id);
                                }}
                              >
                                <Box
                                  component="span"
                                  aria-hidden="true"
                                  sx={{
                                    fontSize: "1.1rem",
                                    lineHeight: 1,
                                  }}
                                >
                                  ×
                                </Box>
                              </IconButton>
                            </Tooltip>
                          </Stack>
                        ) : null}
                      </Stack>
                    </Paper>
                  );
                })}
              </Stack>
            )}
          </Stack>
        </Box>

        {unrankedCriteria.length > 0 ? (
          <>
            <Divider />

            <Box>
            <Stack spacing={0.75}>
              <Box>
                <Typography variant="subtitle2">
                  {permitEdit ? "Available criteria" : "Not ranked"}
                </Typography>

                <Typography
                  variant="caption"
                  color="text.secondary"
                >
                  {permitEdit
                    ? "Adding a criterion places it at the end of the current ranking."
                    : "These criteria are not included in the stored ranking."}
                </Typography>
              </Box>

              {unrankedCriteria.map((criterion) => {
                const criterionName = criterion.name || criterion.id;

                return (
                  <Paper
                    key={criterion.id}
                    variant="outlined"
                    sx={{
                      p: 1,
                      borderRadius: 2,
                      borderColor: "divider",
                      bgcolor: "background.paper",
                    }}
                  >
                    <Stack
                      direction="row"
                      spacing={1}
                      alignItems="center"
                      justifyContent="space-between"
                    >
                      <Typography
                        variant="body2"
                        sx={{
                          minWidth: 0,
                          overflowWrap: "anywhere",
                        }}
                      >
                        {criterionName}
                      </Typography>

                      {permitEdit ? (
                        <Button
                          size="small"
                          variant="outlined"
                          color="info"
                          aria-label={`Add ${criterionName} to ranking`}
                          onClick={() => {
                            handleAdd(criterion.id);
                          }}
                          sx={{
                            flexShrink: 0,
                          }}
                        >
                          Add
                        </Button>
                      ) : null}
                    </Stack>
                  </Paper>
                );
              })}
            </Stack>
            </Box>
          </>
        ) : null}
      </Stack>
    </Box>
  );
};

export default CriteriaPreferenceOrderView;
