// Generated by ModelForge.
// Registers this Evaluation Structure View.
// See IMPLEMENTATION_GUIDE.md.

import { EVALUATION_STAGES } from "../../evaluationStages";
import CriteriaPreferenceOrderView from "./CriteriaPreferenceOrderView";
import { buildInitialEvaluation } from "./operations/buildInitialEvaluation";

export const criteriaPreferenceOrderStructure = Object.freeze({
  key: "criteriaPreferenceOrder",
  stage: EVALUATION_STAGES.CRITERIA_WEIGHTING,
  implementationStatus: "scaffold",
  View: CriteriaPreferenceOrderView,
  buildInitialEvaluation,
});
