from pathlib import Path

import pytest
from fastapi import HTTPException

from schemas.scaffold_assets import ScaffoldAssetItem
from services import scaffold_assets


def _write_model_definition(
    path: Path,
    *,
    status: str = "scaffold",
    marker: bool = True,
) -> None:
    marker_line = "# Generated by ModelForge.\n" if marker else "# Manual model\n"
    path.write_text(
        f'{marker_line}implementation_status="{status}"\n',
        encoding="utf-8",
    )


def _write_plugin_index(
    path: Path,
    *,
    status: str = "scaffold",
    marker: bool = True,
) -> None:
    marker_line = "// Generated by ModelForge.\n" if marker else "// Repository plugin\n"
    path.write_text(
        f'{marker_line}implementationStatus: "{status}"\n',
        encoding="utf-8",
    )


def _asset_by_key(items: list[ScaffoldAssetItem], key: str) -> ScaffoldAssetItem:
    return next(item for item in items if item.key == key)


def test_model_assets_fail_closed_until_the_definition_is_an_active_scaffold(
    tmp_path: Path,
) -> None:
    models_root = tmp_path / "DecisionModelsService/models"
    scaffold_model = models_root / "scaffold_model"
    ready_model = models_root / "ready_model"
    manual_model = models_root / "manual_model"
    incomplete_model = models_root / "incomplete_model"

    for path in (scaffold_model, ready_model, manual_model, incomplete_model):
        path.mkdir(parents=True)
    _write_model_definition(scaffold_model / "definition.py")
    _write_model_definition(ready_model / "definition.py", status="ready")
    _write_model_definition(manual_model / "definition.py", marker=False)

    assets = scaffold_assets.build_scaffold_assets(tmp_path)

    assert _asset_by_key(assets.models, "scaffold_model").model_dump() == {
        "kind": "model",
        "key": "scaffold_model",
        "locations": ["DecisionModelsService/models/scaffold_model"],
        "missingLocations": [],
        "stage": None,
        "deletable": True,
        "protected": False,
        "origin": "modelForge",
        "deleteDisabledReason": None,
    }
    for key in ("ready_model", "manual_model", "incomplete_model"):
        asset = _asset_by_key(assets.models, key)
        assert asset.deletable is False
        assert asset.protected is True
        assert asset.origin == "repository"
        assert asset.deleteDisabledReason


def test_delete_rechecks_model_protection_and_only_removes_an_active_scaffold(
    tmp_path: Path,
) -> None:
    models_root = tmp_path / "DecisionModelsService/models"
    protected_model = models_root / "protected_model"
    scaffold_model = models_root / "scaffold_model"
    protected_model.mkdir(parents=True)
    scaffold_model.mkdir(parents=True)
    _write_model_definition(protected_model / "definition.py", marker=False)
    _write_model_definition(scaffold_model / "definition.py")

    with pytest.raises(HTTPException) as exc_info:
        scaffold_assets.delete_scaffold_asset(
            project_root=tmp_path,
            kind="model",
            key="protected_model",
        )

    assert exc_info.value.status_code == 409
    assert exc_info.value.detail == {
        "message": "This model is not an active Model Forge scaffold.",
        "kind": "model",
        "key": "protected_model",
    }
    assert protected_model.exists()

    result = scaffold_assets.delete_scaffold_asset(
        project_root=tmp_path,
        kind="model",
        key="scaffold_model",
    )

    assert result.deletedLocations == ["DecisionModelsService/models/scaffold_model"]
    assert not scaffold_model.exists()
    assert protected_model.exists()


def test_evaluation_assets_require_complete_generated_scaffolds_before_deletion(
    tmp_path: Path,
) -> None:
    backend_root = tmp_path / "Backend/modules/decisionPlugins/evaluations/structures"
    frontend_root = tmp_path / "Frontend/src/features/decisionPlugins/evaluations/structures"

    generated_backend = backend_root / "generated"
    generated_frontend = frontend_root / "generated"
    manual_backend = backend_root / "manual"
    manual_frontend = frontend_root / "manual"
    partial_backend = backend_root / "partial"
    for path in (
        generated_backend,
        generated_frontend,
        manual_backend,
        manual_frontend,
        partial_backend,
    ):
        path.mkdir(parents=True)
    _write_plugin_index(generated_backend / "index.js")
    _write_plugin_index(generated_frontend / "index.js")
    _write_plugin_index(manual_backend / "index.js", marker=False)
    _write_plugin_index(manual_frontend / "index.js", marker=False)
    _write_plugin_index(partial_backend / "index.js")

    assets = scaffold_assets.build_scaffold_assets(tmp_path)
    assert _asset_by_key(assets.evaluationStructures, "generated").deletable is True
    assert _asset_by_key(assets.evaluationStructures, "manual").protected is True
    partial = _asset_by_key(assets.evaluationStructures, "partial")
    assert partial.protected is True
    assert partial.deletable is False
    assert partial.deleteDisabledReason == (
        "This evaluation structure is partial and must be inspected manually."
    )

    with pytest.raises(HTTPException) as exc_info:
        scaffold_assets.delete_scaffold_asset(
            project_root=tmp_path,
            kind="evaluationStructure",
            key="partial",
        )
    assert exc_info.value.status_code == 409
    assert partial_backend.exists()

    scaffold_assets.delete_scaffold_asset(
        project_root=tmp_path,
        kind="evaluationStructure",
        key="generated",
    )
    assert not generated_backend.exists()
    assert not generated_frontend.exists()
    assert manual_backend.exists()
    assert manual_frontend.exists()


def test_parameter_assets_require_complete_generated_scaffolds_before_deletion(
    tmp_path: Path,
) -> None:
    backend_root = tmp_path / "Backend/modules/decisionPlugins/modelParameters/structures"
    frontend_root = tmp_path / "Frontend/src/features/decisionPlugins/modelParameters/fields"

    generated_backend = backend_root / "generated"
    generated_frontend = frontend_root / "generated"
    manual_backend = backend_root / "manual"
    manual_frontend = frontend_root / "manual"
    backend_only = backend_root / "selectGlobal"
    for path in (
        generated_backend,
        generated_frontend,
        manual_backend,
        manual_frontend,
        backend_only,
    ):
        path.mkdir(parents=True)
    _write_plugin_index(generated_backend / "index.js")
    _write_plugin_index(generated_frontend / "index.js")
    _write_plugin_index(manual_backend / "index.js", marker=False)
    _write_plugin_index(manual_frontend / "index.js", marker=False)
    _write_plugin_index(backend_only / "index.js")

    assets = scaffold_assets.build_scaffold_assets(tmp_path)
    assert _asset_by_key(assets.parameterStructures, "generated").deletable is True
    assert _asset_by_key(assets.parameterStructures, "manual").protected is True
    partial = _asset_by_key(assets.parameterStructures, "selectGlobal")
    assert partial.protected is True
    assert partial.deletable is False
    assert partial.deleteDisabledReason == (
        "This parameter structure is partial and must be inspected manually."
    )

    with pytest.raises(HTTPException) as exc_info:
        scaffold_assets.delete_scaffold_asset(
            project_root=tmp_path,
            kind="parameterStructure",
            key="selectGlobal",
        )
    assert exc_info.value.status_code == 409
    assert backend_only.exists()

    scaffold_assets.delete_scaffold_asset(
        project_root=tmp_path,
        kind="parameterStructure",
        key="generated",
    )
    assert not generated_backend.exists()
    assert not generated_frontend.exists()


def test_delete_scaffold_asset_rejects_locations_outside_project_root(
    monkeypatch,
    tmp_path: Path,
) -> None:
    malicious_asset = ScaffoldAssetItem(
        kind="model",
        key="demo_model",
        locations=["../../outside"],
        missingLocations=[],
        deletable=True,
    )

    monkeypatch.setattr(
        scaffold_assets,
        "_find_asset_by_kind_and_key",
        lambda *args, **kwargs: malicious_asset,
    )

    with pytest.raises(HTTPException) as exc_info:
        scaffold_assets.delete_scaffold_asset(
            project_root=tmp_path,
            kind="model",
            key="demo_model",
        )

    assert exc_info.value.status_code == 400
    assert exc_info.value.detail["message"] == "Asset path resolves outside project root."
